<?php
 /**
 * GoMage.com
 *
 * GoMage Feed Pro
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2011 GoMage.com (http://www.gomage.com)
 * @author       GoMage.com
 * @license      http://www.gomage.com/licensing  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 2.1
 * @since        Class available since Release 1.0
 */
	
	$feed = $this->getFeed();
	
	if($data = $this->getFeed()->getContent()){
		
		$data = json_decode($data, true);
		
	}else{
		$data = array();
	}
	
	
	
?>
<div class="entry-edit">
	
	<div class="entry-edit-head">
    	<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Fields Mapping')?></h4>
    	<div class="form-buttons">
    		<button style="" onclick="window.open('http://www.gomage.com/faq/extensions/feed-pro')" class="scalable go" type="button" id="feed_pro_help"><span>Feed Pro Help</span></button>
    	</div>
	</div>
	<div id="content_fieldset" class="fieldset ">
		
		<div class="left">
			<p style="clear:both;padding-bottom:5px;overflow:hidden;">
				<label style="float:left;margin-right:20px; "><span style="float:left;margin-right:10px;"><?php echo $this->__('Show Header')?></span>
				<select style="width:50px;" name="show_headers">
					<option value="1" <?php if(intval($feed->getShowHeaders()) == 1 ):?> selected="selected" <?php endif;?>><?php echo $this->__('Yes');?></option>
					<option value="0" <?php if(intval($feed->getShowHeaders()) == 0 ):?> selected="selected" <?php endif;?>><?php echo $this->__('No');?></option>
				</select>
				</label>
	
				<label style="float:left;margin-right:20px; "><span style="float:left;margin-right:10px;"><?php echo $this->__('Delimiter')?></span>
				<select style="width:100px;" name="delimiter">
					
					<option value="comma" <?php if(($feed->getDelimiter()) == 'comma' || !$feed->getDelimiter()):?> selected="selected" <?php endif;?>><?php echo $this->__('Comma');?></option>
					<option value="tab" <?php if(($feed->getDelimiter()) == 'tab' ):?> selected="selected" <?php endif;?>><?php echo $this->__('Tab');?></option>
					<option value="colon" <?php if(($feed->getDelimiter()) == 'colon' ):?> selected="selected" <?php endif;?>><?php echo $this->__('Colon');?></option>
					<option value="space" <?php if(($feed->getDelimiter()) == 'space' ):?> selected="selected" <?php endif;?>><?php echo $this->__('Space');?></option>
					<option value="vertical pipe" <?php if(($feed->getDelimiter()) == 'vertical pipe' ):?> selected="selected" <?php endif;?>><?php echo $this->__('Vertical pipe');?></option>
					<option value="semi-colon" <?php if(($feed->getDelimiter()) == 'semi-colon' ):?> selected="selected" <?php endif;?>><?php echo $this->__('Semi-colon');?></option>
					
				</select>
				</label>

				<label style="float:left; margin-right:20px;"><span style="float:left;margin-right:10px; "><?php echo $this->__('Enclosure')?></span>
				<select style="width:70px;" name="enclosure">
					
					<option value="2" <?php if(($feed->getEnclosure()) == 2 || !$feed->getDelimiter()):?> selected="selected" <?php endif;?>>"</option>
					<option value="1" <?php if(($feed->getEnclosure()) == 1):?> selected="selected" <?php endif;?>>'</option>
					<option value="3" <?php if(($feed->getEnclosure()) == 3):?> selected="selected" <?php endif;?>> </option>
					
				</select>
				</label>
			</p>
			<p style="clear:both">
				<label><span style="float:left; width: 170px;"><?php echo $this->__('Remove line break symbols')?></span>
				<select style="width:50px;" name="remove_lb">
					<option value="1" <?php if(intval($feed->getRemoveLb()) == 1 ):?> selected="selected" <?php endif;?>><?php echo $this->__('Yes');?></option>
					<option value="0" <?php if(intval($feed->getRemoveLb()) == 0 ):?> selected="selected" <?php endif;?>><?php echo $this->__('No');?></option>
				</select>
				</label><br/>
				<small><?php echo $this->__('This is the specific option that allows to remove line break symbols from a data feed.')?></small>
			</p>			
			<p style="clear:both">
				<label><?php echo $this->__('Use Amazon Header')?></label>
				<script type="text/javascript">
					function gfp_changeAdditionHeader(control){
						if (control.value == 1){
							$('addition_header').show();
						}else{
							$('addition_header').hide();
						}
					}
				</script>
				<select name="use_addition_header" onchange="gfp_changeAdditionHeader(this)">
					<option value="1" <?php if(intval($feed->getUseAdditionHeader()) == 1 ):?> selected="selected" <?php endif;?>><?php echo $this->__('Yes');?></option>
					<option value="0" <?php if(intval($feed->getUseAdditionHeader()) == 0 ):?> selected="selected" <?php endif;?>><?php echo $this->__('No');?></option>
				</select>
				<br/>
				<textarea id="addition_header" name="addition_header" style="width:470px;margin-top:5px;<?php if(intval($feed->getUseAdditionHeader()) == 0 ):?>display:none;<?php endif; ?>"><?php echo $feed->getData('addition_header'); ?></textarea>
			</p>
			<?php if($feed->getId()>0):?>
    			<p style="clear:both">
    				<label style="float: left; margin-right: 20px;">
    					<span style="float:left;margin-right: 10px;"><?php echo $this->__('System')?></span>
        				<select name="feed_system" id="feed_system" onchange="GomageFeedAdmin.setSystem(this.value)">    										
        				</select>
    				</label>				
    				<label style="float: left; margin-right: 20px;">
    					<span style="float:left;margin-right: 10px;"><?php echo $this->__('Template')?></span>
        				<select name="feed_section" id="feed_section">					
        				</select>
    				</label>				
    				<button onclick="GomageFeedAdmin.submit(1, $('feed_section').value);return false;" class="button"><span><span><?php echo $this->__('Import');?></span></span></button>				
    			</p>
			<?php endif; ?>
		</div>
		<div class="right">
			<?php if($feed->getId()>0):?>
			<p style="clear:both;margin-bottom:7px;overflow:hidden;zoom:1;"><button onclick="$('<?php echo $this->getHtmlId() ?>-flash').setStyle({display:'block'});return false;" class="button"><span><span><?php echo $this->__('Import Fields Settings');?></span></span></button></p>
			<div id="<?php echo $this->getHtmlId() ?>" class="uploader">
                <div class="buttons">        
                    <div id="<?php echo $this->getHtmlId() ?>-install-flash" style="display:none">
                        <?php echo Mage::helper('media')->__('This content requires last version of Adobe Flash Player. <a href="%s">Get Flash</a>', 'http://www.adobe.com/go/getflash/') ?>
                    </div>
                </div>
                <div class="clear"></div>
                <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template">
                    <div id="{{id}}" class="file-row">
                    <span class="file-info">{{name}} ({{size}})</span>
                    <span class="delete-button"><?php echo $this->getDeleteButtonHtml() ?></span>
                    <span class="progress-text"></span>
                    <div class="clear"></div>
                    </div>
                </div>
                <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template-progress">
                    {{percent}}% {{uploaded}} / {{total}}
                </div>
            </div>
			<p style="clear:both;margin-bottom:7px;overflow:hidden;zoom:1;"><button onclick="setLocation('<?php echo $this->getUrl('*/*/mappingexport', array('id'=>$feed->getId()))?>');return false;" class="button"><span><span><?php echo $this->__('Export Fields Settings');?></span></span></button></p>
			<p style="clear:both;margin-bottom:7px;overflow:hidden;zoom:1;"><button style="width: 145px;" onclick="setLocation('<?php echo $this->getUrl('*/*/mappingexportftp', array('id'=>$feed->getId()))?>');return false;" class="button"><span><span><?php echo $this->__('Export Fields to Server');?></span></span></button></p>
			<?php else:?>
			<script type="text/javascript">				
				function showImportNotice(){
					if(typeof notice_timeout != 'undefined'){
						clearTimeout(notice_timeout);
					}
					$('import-notice').style.display = 'block';
					$('export-notice').style.display = 'none';
					notice_timeout = setTimeout(function(){
						$('import-notice').style.display = 'none';
					}, 5000)
				}
				function showExportNotice(){
					if(typeof notice_timeout != 'undefined'){
						clearTimeout(notice_timeout);
					}
					$('import-notice').style.display = 'none';
					$('export-notice').style.display = 'block';
					notice_timeout = setTimeout(function(){
						$('export-notice').style.display = 'none';
					}, 5000)
				}
			</script>
			<p style="clear:both;margin-bottom:7px;overflow:hidden;zoom:1;"><button style="float:right" onclick="showImportNotice();return false;" class="button disabled"><span><span><?php echo $this->__('Import Fields Settings');?></span></span></button></p>
			<p style="clear:both;margin-bottom:7px;overflow:hidden;zoom:1;"><button style="float:right" onclick="showExportNotice();return false;" class="button disabled"><span><span><?php echo $this->__('Export Fields Settings');?></span></span></button></p>
			<p id="import-notice" style="clear:both;margin-bottom:7px;overflow:hidden;zoom:1;display:none;"><?php echo $this->__('After you save a new feed for the first time the "Import Fields Settings" button will be available')?></p>
			<p id="export-notice" style="clear:both;margin-bottom:7px;overflow:hidden;zoom:1;display:none;"><?php echo $this->__('After you save a new feed for the first time the "Export Fields Settings" button will be available')?></p>
			<?php endif;?>
		</div>
		<div class="grid" style="clear:both">
		<style>
					.grid table td {vertical-align:middle;}
		</style>
		<table cellspacing="0" cellpadding="0" class="data" style="width:100%;">
			<thead>
				<tr class="headings">
				<th width="20"><?php echo $this->__('Order')?></th>
				<th style="width:160px;"><?php echo $this->__('Field Name')?></th>
				<th><?php echo $this->__('Prefix')?></th>
				<th><?php echo $this->__('Type')?></th>
				<th width="100"><?php echo $this->__('Value')?></th>
				<th><?php echo $this->__('Suffix')?></th>
				<th><?php echo $this->__('Output Type')?></th>
				<th><?php echo $this->__('Symbols Limit')?></th>
				<th style="width:66px;"><?php echo $this->__('Action')?></th>
				</tr>
			</thead>
			<tbody id="mapping-table-body">
				<?php 
				    if(empty($data)){
                		$rows_count = 5;
                	}else{
                		$rows_count = count($data);
                	}				    
                	echo $this->getLayout()->createBlock('adminhtml/template')
				                ->setData('feed', $this->getFeed())
	            				->setTemplate('gomage/feed/item/edit/content/mapping.phtml')->toHtml(); 
	            ?>
			</tbody>
		</table>
		<div class="button-set">
			<script type="text/javascript">
				
				var mappingTotalRows = <?php echo $rows_count?>;
				
				function changeValueType(e, i){
					
					if(e.value == 'static'){
						$('mapping-'+i+'-static-value').style.display = 'block';
						$('mapping-'+i+'-attribute-value').style.display = 'none';
					}else{
						$('mapping-'+i+'-static-value').style.display = 'none';
						$('mapping-'+i+'-attribute-value').style.display = 'block';
					}
					
				}
				
				function removeMappingRow(e){
					e.parentNode.parentNode.parentNode.removeChild(e.parentNode.parentNode);
				}
				
				function addColumn(tr, content){
					
					td = document.createElement('td');
					td.innerHTML = content;
					tr.appendChild(td);
					
				}
				
				function addMappingRow(){
					
					var i = ++mappingTotalRows;
					var tr = document.createElement('tr');
					
					var attribute = '<?php echo addslashes($this->getAttributeSelect("[iterator]"));?>';
					
					addColumn(tr, '<div style="padding:0 2px;border-color:#AAAAAA #C8C8C8 #C8C8C8 #AAAAAA;border-style:solid;border-width:1px;"><input style="width:100%;border:0;padding:0;" class="input-text" name="field['+i+'][order]" value="" /></div>');
					addColumn(tr, '<div style="padding:0 2px;border-color:#AAAAAA #C8C8C8 #C8C8C8 #AAAAAA;border-style:solid;border-width:1px;"><input style="width:100%;border:0;padding:0;" type="text" class="input-text" name="field['+i+'][name]" value="" /></div>');
					addColumn(tr, '<div style="padding:0 2px;border-color:#AAAAAA #C8C8C8 #C8C8C8 #AAAAAA;border-style:solid;border-width:1px;"><input style="width:100%;border:0;padding:0;"type="text" class="input-text" name="field['+i+'][prefix]" value="" /></div>');
					addColumn(tr, '<div style="margin: 2px;"><select style="width:100%;" onchange="changeValueType(this, '+i+')" type="text" name="field['+i+'][type]"><option value="attribute"><?php echo $this->__('Attribute')?></option><option value="static"><?php echo $this->__('Static Value')?></option></select></div>');
					addColumn(tr, '<input style="width:98%; display:none;" id="mapping-'+i+'-static-value" type="text" class="input-text" name="field['+i+'][static_value]" value="" />'+attribute.replace(/\[iterator\]/g, i));
					addColumn(tr, '<div style="padding:0 2px;border-color:#AAAAAA #C8C8C8 #C8C8C8 #AAAAAA;border-style:solid;border-width:1px;"><input style="width:100%;border:0;padding:0;" type="text"  class="input-text" name="field['+i+'][sufix]" value="" /></div>');
					addColumn(tr, '<div style="margin: 2px;"><select style="width:100%;" type="text" name="field['+i+'][output_type]"><option selected="selected" value=""><?php echo $this->__('Default')?></option><option value="int"><?php echo $this->__('Integer')?></option><option value="float"><?php echo $this->__('Float')?></option><option value="striptags"><?php echo $this->__('Striptags')?></option><option value="htmlspecialchars"><?php echo $this->__('Encode special chars')?></option><option value="htmlspecialchars_decode"><?php echo $this->__('Decode special chars')?></option><option value="delete_space"><?php echo $this->__('Delete Space')?></option></select></div>');
					addColumn(tr, '<div style="padding:0 2px;border-color:#AAAAAA #C8C8C8 #C8C8C8 #AAAAAA;border-style:solid;border-width:1px;"><input style="width:100%;border:0;padding:0;" class="input-text" name="field['+i+'][limit]" value="" /></div>');
					addColumn(tr, '<button onclick="removeMappingRow(this);return false;" class="button"><span><span><?php echo $this->__('Remove')?></span></span></button>');
					
					$('mapping-table-body').appendChild(tr);
					
				}
				
			</script>
			<p style="margin-top:10px;"><button onclick="addMappingRow();return false;" class="button"><span><span><?php echo $this->__('Add New Row')?></span></span></button></p>
		</div>
		</div>
	</div>
</div>

<?php if($feed->getId()>0):?>
    <script type="text/javascript">
    //<![CDATA[
    
    var maxUploadFileSizeInBytes = <?php echo $this->getDataMaxSizeInBytes() ?>;
    var maxUploadFileSize = '<?php echo $this->getDataMaxSize() ?>';
    
    <?php echo $this->getJsObjectName() ?> = new Flex.Uploader('<?php echo $this->getHtmlId() ?>', '<?php echo $this->getUploaderUrl('media/uploader.swf') ?>', <?php echo $this->getConfigJson() ?>);
    
    <?php echo $this->getJsObjectName() ?>.onFilesComplete = function(completedFiles){
        completedFiles.each(function(file){
            GomageFeedAdmin.submit(0, file.name);
            <?php echo $this->getJsObjectName() ?>.removeFile(file.id);
        });
        $('<?php echo $this->getHtmlId() ?>-flash').setStyle({display:'none'});
    }
     
    if ($('<?php echo $this->getHtmlId() ?>-flash') != undefined) {
        $('<?php echo $this->getHtmlId() ?>-flash').setStyle({display:'none'});
    } 
    
    //]]>
    </script>
<?php endif; ?> 













