<div class="banner-left"><img src="<?php echo $this->getSkinUrl(); ?>images/banner-one.png" alt="" />
        <div class="column-top" style="padding-top: 9px; height: 26px;">Like us on Facebook</div>
        <div class="banner-pic"><iframe src="http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2FevogueSocial&amp;width=199&amp;colorscheme=light&amp;show_faces=false&amp;stream=false&amp;header=false&amp;height=78" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:199px; height:78px;" allowTransparency="true"></iframe></div>
        <div class="banner-explanation">Get exclusive access to special offers and behind the scenes content</div>
</div>