<div id="colleft">
	<div id="panel">
		
			<div id="hidePanel">
				<div id="hide-container"><span>Hide feedback</span></div>
			</div>
			<?php echo $this->getEmbed(); ?>


	</div>

</div>

	<div id="showPanel">
		<div id="show-container"><span>Tell us what brands you'd like to see</span></div>
	</div>



<script type="text/javascript">

	var $j = jQuery.noConflict();
    	$j("#showPanel").css("display","none");
    	
    	$j(document).ready(function () {
			
			var survey = $j("#surveyMonkeyInfo");
			
			if(survey.is(":visible")) {
				$j("#showPanel").css("display","block");
				$j(survey).wrap('<div id="panel" />');
				$j('#survey-container').text('<div id="survey-wrap"><a href="#">&laquo; Hide Feedback</a></div>');
			}
			

		 $j("#hidePanel").click(function(){
			 $j("#panel").animate({marginTop:"-313px"}, 500 );
			 $j("#colleft").animate({height:"0px", opacity:0}, 400 );
			 $j("#showPanel").show("normal").animate({height:"40px", opacity:1}, 200);
			 //$j("#colright").animate({marginLeft:"50px"}, 500);
		 });

		 $j("#showPanel").click(function(){
			 //$j("#colright").animate({height:"200px"}, 200);
			 $j("#panel").animate({marginTop:"0px"}, 400 );
			 $j("#colleft").animate({height:"313px", opacity:1}, 400 );
			 $j("#showPanel").animate({height:"0px", opacity:0}, 600).hide("slow");
		 });
		
		
		});

</script>