<div class="account-edit">
<div class="page-title black-title-bar">
    <?php echo $this->__('Edit Account Information') ?>
</div>
<div class="account-information-page">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" enctype="multipart/form-data">
<div class="fieldset">
	<!--[if IE 7]>
	<style type="text/css">
		#gender-input-box {
			position:relative;
			left:-90px;
		}
	</style>
	<![endif]-->
    <?php echo $this->getBlockHtml('formkey')?>
    <span class="black-title-med"><?php echo $this->__('Account Information') ?></span>
    <div class="small-spacer"></div>
    <ul class="form-list">
        <li class="fields">
            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
        </li>
        <li>
            <label for="email" class="required"><span class="black-title-small"><em>*</em><?php echo $this->__('Email Address') ?></span></label>
            <div class="input-box">
                <input type="text" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
            </div>
        </li>
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
        <?php if($_dob->isEnabled() || $_taxvat->isEnabled() || $_gender->isEnabled()): ?>
        <li class="fields">
            <?php if ($_dob->isEnabled()): ?>
            <div class="field"><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></div>
            <?php endif ?>
            <?php if ($_taxvat->isEnabled()): ?>
            <div class="field"><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></div>
            <?php endif ?>
            <?php if ($_gender->isEnabled()): ?>
            <div class="field"><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></div>
            <?php endif ?>
        </li>
        <?php endif ?>
        <li class="control">
            <div class="input-box">
                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" />
            </div>
            <span class="change-pw-label" for="change_password"><?php echo $this->__('Change Password') ?></span>
        </li>
    </ul>
</div>
<?php $userDefinedAttributes = $this->getLayout()->getBlock('customer_form_user_attributes');?>
<?php if ($userDefinedAttributes):?>
    <?php echo $userDefinedAttributes->setEntity($this->getCustomer())->toHtml(); ?>
<?php endif;?>
<div class="fieldset" style="display:none;">
    <ul class="form-list">
        <li class="fields">
            <div class="field">
                <label for="current_password"><span class="black-title-small"><?php echo $this->__('Current Password') ?></span></label>
                <div class="input-box">
                    <input type="password" class="input-text" name="current_password" id="current_password" />
                </div>
            </div>
        </li>
        <li class="fields">
            <div class="field">
                <label for="password"><span class="black-title-small"><?php echo $this->__('New Password') ?></span></label>
                <div class="input-box">
                    <input type="password" class="input-text validate-password" name="password" id="password" />
                </div>
            </div>
            <div class="field">
                <label for="confirmation"><span class="black-title-small"><?php echo $this->__('Confirm New Password') ?></span></label>
                <div class="input-box">
                    <input type="password" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                </div>
            </div>
        </li>
    </ul>
</div>
<div class="buttons-set form-buttons">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Go back') ?></a></p>
    <button type="submit" class="button" title="<?php echo $this->__('Save') ?>"><span>SAVE</span></button>
</div>
<p class="required"><?php echo $this->__('* Required Fields') ?></p>
</form>
</div>
</div>


<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(4).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(4).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }
    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>
