<label for="<?php echo $this->getHtmlId(0)?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->getLabel() ?></label>
<div class="input-box">
    <input type="text" id="<?php echo $this->getHtmlId(0)?>" name="<?php echo $this->getFieldName('')?>" value="<?php echo $this->getEscapedValue(0) ?>" class="input-text<?php echo $this->getHtmlClass(); ?>" />
</div>
<?php if ($this->getLineCount() > 1): ?>

    <?php for ($i = 1, $lc = $this->getLineCount(); $i < $lc; $i ++): ?>
</li>
<li class="add-field">
<div class="input-box ">
    <input type="text" id="<?php echo $this->getHtmlId($i)?>" name="<?php echo $this->getFieldName('')?>" value="<?php echo $this->getEscapedValue($i) ?>" class="input-text<?php echo $this->getLineHtmlClass();?>" />
</div>
    <?php endfor; ?>
<?php endif;?>
