<?php $personalUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . Mage::getModel('customer/customer')->load(Mage::getSingleton('customer/session')->getId())->getCustomerurl(); ?>
<?php $smallShareLogo = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'brandid-square-100.png'; ?>
<?php $bigShareLogo = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'brandid-square-big.png'; ?>

<?php if($this->showReferralUrl()) { ?>
<!-- @nelkaake Added on Saturday June 26, 2010: BEGIN referral code/url/email fieldset -->
<div class="share-invitation-link black-title-bar"><?php echo $this->__('Share your personal invitation link'); ?></div>
	<div class="share-invitation-link-box">
        <?php if($this->showReferralUrl()): ?>

		<div class="invitation-link">
            <div class="invitation-instructions">
            	You will be credited for anyone using your link to signup
            </div>
            <div class="urlcode-input-box">
                <span><?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?></span><input type="text" name="referral_url" style="background: #eaeaea;" value="<?php echo Mage::getModel('customer/customer')->load(Mage::getSingleton('customer/session')->getId())->getCustomerurl(); ?>" 
                    title="<?php echo $this->__('Your Referral URL') ?>" class="input-text" id="referral_url" disabled="disabled" />
	            <button class="edit"><span><?php echo $this->__('Edit'); ?></span></button>
            </div>
			<span id="customer-url-validation-message"></span>        

		</div>

		<?php endif; ?>

	    <div class="social-share">
	        <div class="social-share-images">
	        <?php /*?><a href="http://www.facebook.com/sharer.php?u=<?php echo $this->getReferralUrl(); ?>" target="_blank"><img class="facebook" src="<?php echo $this-> getSkinUrl(); ?>images/facebook.png" width="48" height="48" title="post this on facebook"/></a><?php */?>
	        
	        <div class="facebok-share">
	        	<div id="fb-root"></div>

				<fb:send href="<?php echo $personalUrl;?>" font=""></fb:send>

		        <!-- div class="f-trans"></div-->
	        </div>
			<div class="f-text">via Facebook</div>
	    
	    </div>    


		        	        
			</div>
	        <div class="twitter-share">
			
			<div class="tweet-this-button">
				<a href="https://twitter.com/share"
					class="twitter-share-button"
					data-url="<?php echo $personalUrl ;?>"
					data-text="Money, power, auto-delivered undies. I got #BRANDiD. Use my invite "
					data-count="none"
					data-via="getbrandid">
					Tweet
				</a>
				<script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
			</div>
			
			
<!--
	        	<div class="t-trans" style="display:block;"></div>
-->
				<div class="t-text">on Twitter</div>
				

	        </div>
	        
	        <div class="twitter-share">
 				<a href="https://www.tumblr.com/share/photo?source=<?php echo urlencode($bigShareLogo) ?>&caption=<?php echo urlencode('Tumblr. Tumblid. Branblr. <strong>BRANDiD.</strong>') ?>&clickthru=<?php echo urlencode($personalUrl) ?>" title="Share on Tumblr" target="_blank" style="display:inline-block; text-indent:-9999px; overflow:hidden; width:61px; height:20px; background:url('https://platform.tumblr.com/v1/share_2.png') top left no-repeat transparent;">Share on Tumblr</a>
				
				
				<div class="t-text">on Tumblr</div>
			</div>
	        
	        
	        
	    </div>
	</div>
<?php }?>

<!-- @nelkaake Added on Saturday June 26, 2010: END referral code/url/email fieldset -->

<script type="text/javascript">
	Event.observe($$('.urlcode-input-box button.edit')[0], 'click', function(){
		if ($('referral_url').readAttribute('disabled')) {
			this.select('span')[0].innerHTML = 'save';
			this.setAttribute('disabled', 'disabled');
			this.setStyle({ background: '#777' });
			$('referral_url').setStyle({ background: '#FFFBCC' });
			$('referral_url').removeAttribute('disabled');
		} else {
			jQuery('.urlcode-input-box').css("background-color","#FFFBCC");
			jQuery('#referral_url').animate({ backgroundColor: '#eaeaea' }, 2000);
			jQuery('.urlcode-input-box').animate({ backgroundColor: '#eaeaea' }, 2000);		
			$('customer-url-validation-message').addClassName('loading');
			$('customer-url-validation-message').innerHTML = 'Saving your username...';		

			$('referral_url').setAttribute('disabled', 'disabled');	
			this.select('span')[0].innerHTML = 'edit';
			
			this.removeAttribute('disabled');
			this.setStyle({ background: '#d2002b' });			
			
			var ajax = new Ajax.Request('/index.php/customerurl/unique/save',{
				method: 'post',
				parameters: { customerurl: $('referral_url').value }, 
				onSuccess: function(transport) {
					window.location.reload();
				}
			});
		}
	});
	
	var timer = 0;
	Event.observe($('referral_url'), 'keyup', function(){
		clearTimeout(timer);
		
		$('customer-url-validation-message').addClassName('loading');
		$('customer-url-validation-message').innerHTML = 'Validating your username...';
		
		timer = setTimeout('verify()', 1000);
	});
	
	function verify() {
	
		$$('.urlcode-input-box button.edit')[0].setAttribute('disabled', 'disabled');
		$$('.urlcode-input-box button.edit')[0].setStyle({ background: '#777' });			
		
		$('customer-url-validation-message').addClassName('loading');
		$('customer-url-validation-message').innerHTML = 'Validating your username...';
		
		var ajax = new Ajax.Request('/index.php/customerurl/unique/verify',{
			method: 'post',
			parameters: { customerurl: $('referral_url').value }, 
			onSuccess: function(transport) {
				var response = eval('new Object(' + transport.responseText + ')');
				$('customer-url-validation-message').removeClassName('loading');
				
				if (response.success == 1) {
					$('customer-url-validation-message').innerHTML = 'Username is available';
					
					$$('.urlcode-input-box button.edit')[0].removeAttribute('disabled');
					$$('.urlcode-input-box button.edit')[0].setStyle({ background: '#d2002b' });			
					
				} else {
					$('customer-url-validation-message').innerHTML = 'Username already taken.';				
				}
			}
		});
	
	}
</script>
