
<?php if($this->showPreferences()): ?>
<!-- @nelkaake Added on Saturday July 1, 2010: BEGIN referral preferences fieldset -->
<a name="preferences"></a><div class="referral-preferences black-title-bar"><?php echo $this->__('Referral Preferences'); ?></div>
<div class="referral-preferences-box">
<form action="<?php echo $this->getUrl('rewardsref/customer/savePref/') ?>" method="post" id="form-validate">
<fieldset class="group-select my_referrals-urlcode_group">
    
    <ul>
        <li>
            <div class="urlcode-checkbox">
                <input type="checkbox" name="rewardsref_notify_on_referral" 
                        <?php if($this->getCustomer()->getRewardsrefNotifyOnReferral()): ?>checked="checked" <?php endif; ?>
                        value="1" 
                        title="<?php echo $this->__('Notify me when I earn points from my referral') ?>" 
                        class="checkbox" id="rewardsref_notify_on_referral" />
                <label for="rewardsref_notify_on_referral"><?php echo $this->__('Notify me when I earn points from my referral') ?></label>
            </div>
        </li>
    </ul>
    <div class="button-set" style="margin-top:0px">
        <button class="form-button rewardsref-button savepreferences" type="submit">Save preferences</button>
    </div>
</fieldset>
</form>
</div>
<!-- @nelkaake Added on Saturday July 1, 2010: END referral preferences fieldset -->

<?php endif ?>