<?php $_element = $this->getElement() ?>
<div class="rule-tree">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $_element->getLegend() ?></h4>
    </div>
    <fieldset id="<?php echo $_element->getHtmlId() ?>" <?php echo $_element->serialize(array('class')) ?>>
        <?php echo $_element->getChildrenHtml() ?>
    </fieldset>
</div>
<script type="text/javascript">
var TargetRuleForm = Class.create(VarienRulesForm, {
    initParam: function ($super, container) {
        $super(container);
        var valueType = container.down('.value-type-chooser');
        if (valueType) {
            valueType.observe('change', this.valueTypeChooser.bind(this, container));
            this.changeValueType(valueType);
        }
    },
    valueTypeChooser: function(container, event) {
        var chooser = Event.findElement(event, 'select');
        if (chooser) {
            this.changeValueType(chooser);
        }
    },
    changeValueType: function(valueTypeСhooser)
    {
        var cooserContainer = valueTypeСhooser.up('.rule-param');
        if (cooserContainer && cooserContainer.next()) {
            var valueSelect = cooserContainer.next().down('select');
            if (valueTypeСhooser.value == 'constant') {
                cooserContainer.next().show();
                if (valueSelect) {
                    valueSelect.disabled = false;
                }
            } else {
                cooserContainer.next().hide();
                if (valueSelect) {
                    valueSelect.disabled = true;
                }
            }
        }
    }
});

var <?php echo $_element->getHtmlId() ?> = new TargetRuleForm('<?php echo $_element->getHtmlId() ?>', '<?php echo $this->getNewChildUrl() ?>');

</script>
