<?php
/**
 * Woopra plugin for Magento 
 *
 * @category    design_default
 * @package     Jira_Woopra
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2010 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */
?>
<?php if($this->getSetting('enabled')) { ?>
	<?php if($this->getSetting('test')) { ?>
	<script type="text/javascript" language="javascript">
    	alert('Woopra is installed but in test mode');
	</script>
	<?php } else { ?>
		<script type="text/javascript">
			var woo_visitor = { name:'<?php echo $this->getSetting('name'); ?>', email:'<?php echo $this->getSetting('email'); ?>', avatar:'<?php echo $this->getSetting('avatar'); ?>', company:'<?php echo $this->getSetting('company'); ?>', city:'<?php echo $this->getSetting('city'); ?>', phone:'<?php echo $this->getSetting('phone'); ?>', cart_items:'<?php echo $this->getSetting('cart_items'); ?>', cart_total:'<?php echo $this->getSetting('cart_total'); ?>'};
			var woo_actions=[{'type':'pageview','title':document.title,'url':window.location.pathname,'category':'<?php echo $this->getSetting('category'); ?>', 'product_price':'<?php echo $this->getSetting('product_price'); ?>', 'product_sku':'<?php echo $this->getSetting('product_sku'); ?>'}];
			(function(){
			    var wsc = document.createElement('script');
			    wsc.type = 'text/javascript';
			    wsc.src = document.location.protocol+'//static.woopra.com/js/woopra.js';
			    wsc.async = true;
			    var ssc = document.getElementsByTagName('script')[0];
			    ssc.parentNode.insertBefore(wsc, ssc);
			})();
		</script>
	<?php } ?>
<?php } ?>