
<script type="text/javascript">

// Other PHP content ///////////////
var currency_map  = <?php echo $this->getCurrencyMapJson(); ?>;

function feignPriceChange() {
    
}

</script>
<div class="slider" onmouseup="sliderNotSliding()" style="display:none;">
	<table cellspacing="0" cellpadding="0">
		<tbody>
			<tr>
			    <td style="vertical-align:middle" class="btn-slider-reduce-points-container">
                    <img class="btn-slider-reduce-points" alt="<?php echo $this->__('Spend one point less'); ?>" 
                            src="<?php echo $this->getSkinUrl('images/rewards/slider/decr_points.gif'); ?>" 
                            id="slider_reduce_points"
                            onclick="rSlider.slider.setValue(rSlider.slider.value-1)" 
                            style="position:relative; top:5px;" />
                </td>
				<td>
					<div class="sliderRail" id="sliderRail">
					   <a style="left: 0%; top: -7px;" class="sliderHandle ui-slider-handle ui-state-default" id="sliderHandle"
							onmousedown="sliderSliding()"  
							onmouseup="sliderNotSliding()"></a>
					</div>
				</td>
			    <td style="vertical-align: middle" class="btn-slider-reduce-points-container">
    				<img class="btn-slider-increase-points" 
                            alt="<?php echo $this->__('Spend one point more'); ?>" 
                            src="<?php echo $this->getSkinUrl('images/rewards/slider/incr_points.gif'); ?>" 
                            id="slider_reduce_points"
                            onclick="rSlider.slider.setValue(rSlider.slider.value+1)" 
                            style="position:relative; top:5px;" />
                </td>
				<td valign="top">
					<div id="sliderCaption" class="sliderCaption" >
						<?php echo ''; ?>
					</div>
				</td>
			</tr>
		</tbody>
	</table>
</div>
<script type="text/javascript">
	document.observe("dom:loaded", function() {
//		rSlider = new PointsSlider('sliderHandle', 'sliderRail', 'sliderCaption', 'redemption_rule_uses');
	});

	// Functions for changing the cursor on the slider
	function sliderSliding() {
		$('sliderRail').addClassName('sliderRail-sliding'); 
		$('sliderHandle').addClassName('sliderHandle-sliding');
	}

	function sliderNotSliding() {
		$('sliderRail').removeClassName('sliderRail-sliding'); 
		$('sliderHandle').removeClassName('sliderHandle-sliding');
	}
</script>
	<input type="hidden" name="redemption_uses" id="redemption_rule_uses"/>

<div class="rangeinput">
	<?php
	$max = Mage::registry('current_product')->getFinalPrice();
	$usable = Mage::getSingleton ( 'rewards/session' )->getCustomer()->getUsablePoints();
	$usable = $usable[1];
	if ($max > ($usable / Mage::registry('pointsPerPound'))) {
		$max = $usable / Mage::registry('pointsPerPound');
	}
	$max = number_format($max, 2);
	?>
	<input type="range" id="range" name="test" min="0" max="<?php echo $max; ?>" value="0" /><br />
	<?php $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?>
	<script type="text/javascript">
	jQuery(":range").rangeinput();
	
	$('redemption_rule').options[1].selected = true;
	Event.observe($$('.wrapper')[0], 'mouseup', function(obj){
		if ($('redemption_rule_uses').value == $('range').value) {
			return;
		} else {
			$('redemption_rule_uses').value = $('range').value;
			if ($('range').value > 0) {
				var newPrice = <?php echo number_format(Mage::registry('current_product')->getFinalPrice(),2); ?> - $('range').value;
				$$('.price-box .price')[$$('.price-box .price').length-1].innerHTML = '<?php echo $currencySymbol; ?>' + parseInt(newPrice) + '.00 with ' + parseInt(pointsPerPound * $('range').value) + ' points';
			} else {
				$$('.price-box .price')[$$('.price-box .price').length-1].innerHTML = '<?php echo $currencySymbol; ?><?php echo number_format(Mage::registry('current_product')->getFinalPrice(),2); ?>';		
			}

		}
	});

	Event.observe($$('.wrapper')[0], 'mousemove', function(obj){
		if ($('redemption_rule_uses').value == $('range').value) {
			return;
		} else {
			$('redemption_rule_uses').value = $('range').value;
			if ($('range').value > 0) {
				var newPrice = <?php echo number_format(Mage::registry('current_product')->getFinalPrice(),2); ?> - $('range').value;
				$$('.price-box .price')[$$('.price-box .price').length-1].innerHTML = '<?php echo $currencySymbol; ?>' + parseInt(newPrice) + '.00 with ' + parseInt(pointsPerPound * $('range').value) + ' points';
			} else {
				$$('.price-box .price')[$$('.price-box .price').length-1].innerHTML = '<?php echo $currencySymbol; ?><?php echo number_format(Mage::registry('current_product')->getFinalPrice(),2); ?>';		
			}
		}
	});
	
	document.observe('dom:loaded', function(){
		$$('.product-options select').each(function(obj){
			Event.observe(obj, 'change', function(){
				$('redemption_rule').options[1].selected = true;
			
				$('redemption_rule_uses_container').setStyle({ display: 'block' });			
			});
		
		});
	
	
	});

	</script>
</div>