<?php
$baseurlpath = (string) preg_replace('/\/index\/$/', '', $_SERVER['REQUEST_URI']);
$plaxocb = "$baseurlpath/plaxocb";
//$plaxocb = $_SERVER['REQUEST_URI'] . '../plaxocb'; //might fail on some servers that block ../
?>

<script id="plaxo_script_util" type="text/javascript" ></script>
<script id="plaxo_script_basic" type="text/javascript" ></script>
<script id="plaxo_script_abc_launcher" type="text/javascript" ></script>
<script type="text/javascript">
    // delay loading scripts untill page loaded
    window.onload=function(){
        document.getElementById('plaxo_script_util').src= location.protocol + "//www.plaxo.com/css/m/js/util.js";
        document.getElementById('plaxo_script_basic').src= location.protocol + "//www.plaxo.com/css/m/js/basic.js";
        document.getElementById('plaxo_script_abc_launcher').src= location.protocol + "//www.plaxo.com/css/m/js/abc_launcher.js";
    }
    // OPTIONAL: do something after the new data has been populated in your textarea
    function onABCommComplete() { }
</script>

<a class="plaxo-link" href="#" onclick="showPlaxoABChooser('recipient_list', <?php echo "'$plaxocb'" ?>); return false">Click to add contacts</a>
