<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getCustomerBalanceAmount()): ?>
    <tr>
        <td class="label">
            <?php echo Mage::helper('evogue_customerbalance')->__('Store Credit') ?>
        </td>
        <td>
            <?php echo $this->displayPrices(-$_source->getBaseCustomerBalanceAmount(), -$_source->getCustomerBalanceAmount()); ?>
        </td>
    </tr>
<?php endif; ?>
