
<?php if ($this->hasItems()):?>
<div class="block block-list" id="related-items">
    <div class="block-title">
        <h2 class="cufon"><span><?php echo $this->__('You might also like these') ?></span></h2>
    </div>
    
<!--     <a href="#" id="prev-btn"></a> -->
    
	<div class="block-content">
		
		
    	
		
		<div class="sliders quickie">
			<div class="sliders-footer-container quickie">
			
				<div class="holder">
				
					<div class="slider">
						<ul class="box-content">
						
						<?php $i=0; foreach($this->getItemCollection() as $_item): ?>
					        <li class="item">
					            <div class="item-info">
					                <a href="<?php echo $this->getProductUrl($_item) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(110,164) ?>" width="110" height="164" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
					            </div>
					        </li>
					    <?php endforeach ?>
						</ul>
					</div>
					<div class="left"></div>		
					<div class="right"></div>	
				</div>
			</div>
		</div>







	</div>
	
<!-- 	<a href="#" id="next-btn"></a> -->
	
	
</div>
<?php endif;?>
