<div class="shutl about">
<p>Shutl is a delivery service that lets you get what you want, when you want it. Use this page to estimate delivery charges for your postcode.</p>
</div>
<div class="shutl-london-pic"><img src="<?php echo $this->getSkinUrl(); ?>images/London.jpg" /></div>
<?php /*?><div class="shutl-about-header"></div><?php */?>
<div class="shutl quote">
	<h1><?php echo $this->__('Enter a delivery postcode') ?></h1>
	<form name="product_quote_form" action="<?php echo Mage::getUrl('shutl/quote/product/id/' . $this->getRequest()->getParam('id'))?>" method="post">

		<input type="text" id="postcode" name="postcode" class="postcode" value="<?php echo $this->__('Enter postcode here'); ?>" />
		<br />

		<?php echo $this->getChildHtml('form'); ?>
		<div class="get-quote-div">
		<input type="submit" name="get_quote" class="get_quote" value="<?php echo $this->__('Get quote'); ?>" /></div>
	</form>
	<div class="results"></div>
</div>