<?php
$_helper = Mage::helper('shutl');
$_product = $this->_getProduct();
if ($_product->getPod1Shutl()):
?>
	<div class="clear"></div>
	<div id="shutlService">
		<a href="<?php echo $this->getUrl('shutl/about') . '?id=' . $_product->getId(); ?>" class="shutl_service" alt="Shutl is available">
        <img src="<?php echo $this->getSkinUrl(); ?>images/shutl-quote1.jpg" alt="shutl-quote" />
		</a>
	</div>
	<div class="clear"></div>		
<?php endif; ?>