<?php 
$_opening = $this->getOpeningTime();
$_closing = $this->getClosingTime();	
$_selectedTime = $this->getSelectedTime();
$_selectedTime = urldecode($_selectedTime);

?>
<select id="time" name="time">
	<option value=""><?php echo $this->__('Select a time slot'); ?></option>
<?php for ($i = $_opening; $i < $_closing; $i++):
	$timeSlot = Mage::helper('shutl')->formatTimeSlot($i);
	?>
	<option value="<?php echo $timeSlot; ?>"<?php echo ($_selectedTime == $timeSlot) ? ' selected="selected"' : ''; ?>><?php echo $timeSlot; ?></option>
<?php endfor; ?>
</select>