<?php
/**
 * @see Mage_Catalog_Block_Product_View
 */
$_product = $this->getProduct();
$_tierPrices = $this->getTierPrices();
$assocs = $_product->getTypeInstance()->getChildrenIds($_product->getId());
$ids = array();

foreach($assocs as $k => $v) { $ids[] = $v; }
$rrp = Mage::getModel('catalog/product')
	->getCollection()
	->addAttributeToFilter('entity_id', array('in' => $ids))
	->addAttributeToSort('price', 'DESC')
	->getFirstItem()->getPrice();
	
$rrp = number_format($rrp, 0);


?>
<ul class="quickie-tier-prices" style="display: none;">
	<li class="first"><span class="price">&pound;<?php echo number_format($_product->getPrice(), 0)?></span><span class="big-qty"><?php echo $this->__('1')?>x</span><br /><span class="cheeky-label"><?php echo $this->__('for one night stands');?></span></li>
	<li><span class="price"></span><span class="big-qty"><?php echo $this->__('3')?>x</span><br /><span class="cheeky-label"><?php echo $this->__('\'cos all good things come in threes');?></span></li>
	<li class="last"><span class="price"></span><span class="big-qty"><?php echo $this->__('5')?>x</span><br /><span class="cheeky-label"><?php echo $this->__('to impress that fit bird at work');?></span></li>		
</ul>
</script>
<script type="text/javascript">
    document.observe('dom:loaded', function(){
        $$('.bundle-option-select')[0].observe('change', function(){
            if (this.options[this.selectedIndex].value != '') {
                $$('.quickie-tier-prices')[0].show();
				$$('.quickie-tier-prices li').each(function(o){
                    	o.setStyle({ backgroundColor: '#595959', cursor: 'pointer' });
 					});
             } else {
                $$('.quickie-tier-prices')[0].hide();            
                $$('.quickie-tier-prices li').each(function(o){
                    o.setStyle({ backgroundColor: '#595959', cursor: 'pointer' });
                });                
            }
        });
        var counter = 0;
        $H(bundle.config.options).each(function(obj){
            var located = $H(obj.value.selections);
            located.each(function(o){
                var tierPrices = o.value.tierPrice;
                $$('.quickie-tier-prices span.price')[0].innerHTML = '&pound;' + parseInt(o.value.price) + '<span class="each"> each</span>';
                $$('.quickie-tier-prices span.price')[1].innerHTML = '&pound;' + parseInt(tierPrices[0].website_price) + '<span class="each"> each</span>';
                $$('.quickie-tier-prices span.price')[2].innerHTML = '&pound;' + parseInt(tierPrices[1].website_price) + '<span class="each"> each</span>';
                throw $break;
            });
            var rrp = '<?php echo $rrp; ?>';
            $$('.price-box span.price')[0].innerHTML = 'RRP &pound;' + rrp;
            throw $break;
        });


        $$('ul.quickie-tier-prices li').each(function(obj){
            obj.observe('mouseover', function(){
                if ($$('.input-text.qty')[0].hasClassName('qty-disabled')) { return; }            
                if (this.getStyle('background-color') != 'rgb(210, 0, 43)') {
                    this.setStyle({ backgroundColor: '#000000' });                
                }
            });
            obj.observe('mouseout', function(){
                if ($$('.input-text.qty')[0].hasClassName('qty-disabled')) { return; }            
                if (this.getStyle('background-color') != 'rgb(210, 0, 43)') {
                    this.setStyle({ backgroundColor: '#595959' });
                }
            });

            obj.observe('click', function(){
                if ($$('.input-text.qty')[0].hasClassName('qty-disabled')) { return; }
                this.up().select('li').each(function(o){
                    o.setStyle({ backgroundColor: '#595959', cursor: 'pointer' });
                });
                this.setStyle({ backgroundColor: '#d2002b', cursor: 'default' });

                $$('.input-text.qty')[0].value = parseInt(this.select('span')[2].innerHTML);    
                jQuery($$('.input-text.qty')[0]).keyup();        
            });            
        });
    });
</script>