<?php
/**
 * WDCA - Sweet Tooth Instore
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the SWEET TOOTH (TM) INSTORE
 * License, which extends the Open Software License (OSL 3.0).
 * The Sweet Tooth Instore License is available at this URL: 
 * http://www.sweettoothrewards.com/instore/sweet_tooth_instore_license.txt
 * The Open Software License is available at this URL: 
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * DISCLAIMER
 * 
 * By adding to, editing, or in any way modifying this code, WDCA is 
 * not held liable for any inconsistencies or abnormalities in the 
 * behaviour of this code. 
 * By adding to, editing, or in any way modifying this code, the Licensee
 * terminates any agreement of support offered by WDCA, outlined in the 
 * provided Sweet Tooth Instore License. 
 * Upon discovery of modified code in the process of support, the Licensee 
 * is still held accountable for any and all billable time WDCA spent 
 * during the support process.
 * WDCA does not guarantee compatibility with any other framework extension. 
 * WDCA is not responsbile for any inconsistencies or abnormalities in the
 * behaviour of this code if caused by other framework extension.
 * If you did not receive a copy of the license, please send an email to 
 * support@wdca.ca or call 1-888-699-WDCA(9322), so we can send you a copy 
 * immediately.
 * 
 * @category   [TBT]
 * @package    [TBT_Rewardsinstore]
 * @copyright  Copyright (c) 2011 Sweet Tooth (http://www.sweettoothrewards.com)
 * @license    http://www.sweettoothrewards.com/instore/sweet_tooth_instore_license.txt
 */
?>
<!DOCTYPE HTML>
<html>
    <head>
        <title>Sweet Tooth Instore</title>
        
        <style type="text/css">
            @font-face {
                font-family: HelveticaLT;
                src: url('<?php echo $this->getSkinUrl('fonts/helvetica_light.ttf') ?>') format('truetype');
            } 
            @font-face {
                font-family: HelveticaLT;
                font-weight: bold;
                src: url('<?php echo $this->getSkinUrl('fonts/helvetica_bold.otf') ?>') format('opentype');
            } 
        </style>
        <!--[if IE]>
        <style type="text/css">
            @font-face {
                font-family: HelveticaLT;
                src: src: url('<?php echo $this->getSkinUrl('fonts/helvetica_light.eot') ?>');
            }
            @font-face {
                font-family: HelveticaLT;
                font-weight: bold;
                src: url('<?php echo $this->getSkinUrl('fonts/helvetica_bold.eot') ?>');
            }
        </style>
        <![endif]-->
        
        <?php echo $this->getChildHtml('head') ?>
        <?php /* @TODO: in page/html/head.phtml the Translator script is added... Should we keep Prototype? */ ?>
        <script type="text/javascript">
        //<![CDATA[
            var launchUri = "<?php echo $this->getLaunchUri() ?>";
            var loginUri = "<?php echo Mage::getModel('adminhtml/url')->getUrl('rewardsinstoreadmin/webapp_ajax/main') ?>";
            var formKey = "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>";
            var isLoggedIn = <?php echo $this->isLoggedIn() ? "true" : "false" ?>;
            var storefronts = <?php echo $this->getStorefronts() ?>;
        //]]>
        </script>
        
        <!--[if IE 7]>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/rewardsinstore/webapp/ie7.css') ?>" />
        <![endif]-->
        
        <link rel="apple-touch-icon" type="image" href="<?php echo $this->getSkinUrl('images/rewardsinstore/apple-touch-icon.png') ?>" />
    </head>
    <body>
        <div id="container" style="overflow:hidden; position:relative;">
            <div class="wide2" style="width:1700px;">
                <div class="centerPreLogin" style="position:relative; float:left;"></div>
                <div class="centerPostLogin" style="display:none; position:relative; float:left; left:-775px;">
                    <p>
                        <?php echo $this->__("Logged in as %s", "") ?>
                        <strong>
                            <span id="userFullName"></span>, <span id="storefrontName"></span>
                        </strong>
                        <span id="logoutBar">
                            <a href="#"><?php echo $this->__("Switch user") ?></a>
                        </span>
                    </p>
                </div>
                <div style="clear:both;"></div>
                <div id="loginDiv" class="mainCenter"></div>
                <div id="mainDiv" class="mainCenter" style="display:none; overflow:hidden;"></div>
                <div style="clear: both"></div>
            </div>
                
            <div class="mainFoot" style="position:relative;">
                <div class="footRight">
                    Powered by: 
                    <img src="<?php echo $this->getSkinUrl('images/rewardsinstore/powered_by_logo.png') ?>" style="width:100px; height:18px; vertical-align:bottom;" />
                </div>
                Problems? Contact <a href="http://www.wdca.ca/support" target="_blank">Support</a> for help.
            </div>
        </div>
        <img id="loader" src="<?php echo $this->getSkinUrl('images/rewardsinstore/ajax-loader.gif') ?>" style="position:absolute; opacity:0;" />
    </body>
</html>
