<?php 

/*
* the system checks if 'suppress' is set and if so, then none of the popups pop automatically
*
*/

/*
* redirect the whole page
*
*/

if ($this->getSuppress() == 'true'){
	Mage::getModel('core/cookie')->set('suppress', true); ?>

<script type="text/javascript">document.location.href = 'plans.html';</script>
<?php
}

/*
* phtml condition check
*
*/

if (Mage::getSingleton('customer/session')->isLoggedIn() && !Mage::getModel('core/cookie')->get('suppress')):
?>
<div class="gettingstarted getstarted">
	 
				<div id="panels">
					
					
					<div class="sliders" id="mother">
						
						
						<div class="holder">
							<!-- the element that will be scrolled during the effect -->
							<div id="popup-slide" class="slider">
							
								<!-- our individual panels -->
								<ul>													
									<li>
										<div class="big-fuckoff logo fadein">
										</div>
								 
								 		<div class="popup-title fadein">
								 			<span class="revolutionary">You are now part of something</span><br/>
								 			<span class="revolutionary">Revolutionary</span>
								 		</div>
										<div class="control-box fadein">
											<a id="1-next" class="popup-next" href="#">What's with the 'beta' ?</a>
										</div>
										
									</li> <!-- end panel -->
									
									
									<li class="panel">
										<div class="popup-title fadein">
								 			<span class="revolutionary">Our beta is not yet live</span><br/>
								 			<span class="revolutionary">We're in "stealth mode". Here's why:</span>
								 		</div>

								 
								 		<div class="explain fadein">
								 			<span class="explain-bold">Rome wasn't built in a day.</span><br/>
								 			<span class="explanation">We are not just another online store for men. We are more than that.</span><br/>
								 			<span class="explanation">Ever wondered why women enjoy shopping as much as we hate it?</span><br/>
								 			<span class="explanation">It's because the industry has forgotten about us. We're building something that men can be proud of.</span><br/>

								 		</div>
								 		<div class="explain fadein">
								 			<span class="explanation">But it's not going to be perfect first time out. Our ideas may seem extreme in the beginning.</span><br/>
								 			<span class="explanation">We need your feedback to learn what works and what doesn't.</span><br/>

								 		</div>
								 		<div class="explain fadein">
								 			<span class="explanation">When our beta launches in early 2012, you'll be the first to know. We hope you'll feedback candidly,</span><br/>
								 			<span class="explanation">so together we can build something awesome. For men. Finally.</span><br/>

								 		</div>
																				
										<div class="control-box fadein">
											<a id="2-next" class="popup-next" href="#">Take the 60 second tour</a>
										</div>
									</li>
									
									
									
									<li class="panel plans">
										<div class="popup-title fadein">
								 			<span class="revolutionary">BRANDiD is built around two simple concepts</span><br/>
								 		</div>
								 		<div class="popup-col explain fadein">
								 			<span class="explain-bold">#1 - Plans - because you have more important things to do.</span><br/>
								 			<img class="plans-img" src="<?php echo Mage::getDesign()->getSkinUrl('images/lightbox/beta/plans-preview.png');?>" />

								 			<span class="explanation">Your pants and socks come between you and naked.<br/><br/>
								 			Simply choose your essentials and we deliver monthly. Bosh.<br/><br/>
								 			Plus, we mix it up so you don't get the same boring thing every time.</span>
								 		</div>
								 		
										<div class="control-box fadein">
											<a id="3-prev" class="popup-prev" href="#">go back</a>
											<a id="3-next" class="popup-next" href="#">#2 Boosters</a>
										</div>

									</li>
									
									
									
									<li class="panel boosters">
										<div class="popup-col explain fadein">
								 			<span class="explain-bold">#2 - Boosters - because men shop to solve a problem.</span><br/>
								 			<span class="explanation">Delivered immediately in large quantities and with bulk discounts,</span><br/>
								 			<span class="explanation">Boosters ensure you're not in this situation again any time soon.</span>
								 			<img class="boosters-img" src="<?php echo Mage::getDesign()->getSkinUrl('images/lightbox/beta/boosters.png');?>" />
										</div>
										<div class="popup-col brands-list fadein">
								 			<span class="brands">Adidas Originals</span><br/>
								 			<span class="brands">Alexander McQueen</span><br/>
								 			<span class="brands">Armani</span><br/>
								 			<span class="brands">Calvin Klein</span><br/>
								 			<span class="brands">Converse</span><br/>
								 			<span class="brands">Diesel</span><br/>
								 			<span class="brands">Dior</span><br/>
								 			<span class="brands">Dolce & Gabbana</span><br/>
								 			<span class="brands">Gucci</span><br/>
								 			<span class="brands">Prada</span><br/>
								 			<span class="brands">Roberto Cavalli</span><br/>
								 			<span class="brands">…and 100's more</span>
								 		</div>
										<!--
<div class="popup-col explain fadein">
								 			<span class="explanation">…but if shopping isn't your thing,<br/>go for a Lucky Dip and we'll choose for you.</span>
											<div class="lucky-dip-img">
											</div>
										</div>
-->
										
										
										
										<div class="control-box fadein">
											<a id="4-prev" class="popup-prev" href="#">go back</a>
											<a id="4-next" class="popup-next" href="#">oh, and one more thing</a>
										</div>
									</li>
									
									
									
									<li class="panel loyalty">
										<div class="popup-title fadein">
								 			<span class="revolutionary">Loyalty. Done Properly.</span>
								 		</div>
										<div class="popup-col explain">
								 			<span class="explain-bold fadein">You just earned 100 points.<br/>Well done.</span><br/><br/>
								 			<span class="explanation fadein">You earn points for all kinds of things<br/>
												on BRANDiD, you can even earn double<br/>
												and triple points for really ballsy moves.<br/>
												[HINT: the easiest way is to invite your friends.]<br/><br/>
												Points can be spent on our already discounted Boosters,<br/>
												its pretty much like stealing.</span><br/>
										</div>
										<div class="tie-container fadein">
								 			<div class="tie-img"></div>
											<div class="tie-details">
												<span class="detail">Giorgio Armani Tie</span><br/>
												<span class="detail">RRP £110</span><br/>
												<span class="detail red">FREE WITH 5000 POINTS</span>
											</div>
										</div>
										<div class="popup-col explain friends fadein">Or, get 50 friends to sign up, and we’ll send you a free designer tie, no points needed.</div>
										<div class="control-box fadein">
											<a id="5-prev" class="popup-prev" href="#">go back</a>
											<a id="5-next" class="done" href="/rewardsref/customer/index">Send some invitations</a>
											
											<!-- form name="customer_details" action="/popup/form/page/index/beta/suppress/true">
												<input type="hidden" name="suppress" value="true" />

												
												<input id="5-next" class="done" type="submit" name="submit" value="submit" />

											</form-->
										</div>
									</li>
								</ul>
								
							</div> <!-- end scrollContainer -->
							
							
						</div> <!-- end scroll -->
					</div> <!-- end slider -->
				
				</div> <!-- end panes -->



 	
</div>
<script type="text/javascript">

Ajax.Responders.register({
    onComplete: function(request) {

        if (request.url.indexOf('popup/form/page/index/beta/suppress/true') >= 0) {

			 document.location.href = request.transport.responseText;
        }
    }
});

</script>


<script type="text/javascript">
	
	
	var $j = jQuery.noConflict();
    
    	$j(document).ready(function () {
			init();
			
			$j('.popup-next').each(function(index) {
				$j(this).click(function() {
					var left = parseInt($j("#popup-slide").css("margin-left"));
					$j('#popup-slide').animate({
						marginLeft: left - 790},
						{
						duration:  500,
						easing: 'easeInExpo'
					});
					var name = $j(this).attr('id');
					var delay = function() { doFade(name); };
					setTimeout(delay,500);
				});
			});
			
			$j('.popup-prev').click(function() {
				$j(this).click(function() {
					var left = parseInt($j("#popup-slide").css("margin-left"));
					$j('#popup-slide').animate({
						marginLeft: left + 790},
						{
						duration:  500,
						easing: 'easeInExpo'
						});
				});
			});
	
	
		});
		
	function init() {

		$j(".fadein").each(function(){
		    $j(this).css('opacity','0');
/* 		    $j(this).data("visible","false"); */
		  });
		
		var counter = 0;
		var obj = $j("#popup-slide").children("ul").children("li").eq(0);
		var numFades = $j(obj).find(".fadein").size();
		var target;
		timer1 = setInterval(function() {
			if(counter >= numFades) { 
				clearInterval(timer1);
			 }
			 else {
			 	target = jQuery(obj).find(".fadein").eq(counter);
			 	startFade(target);
				counter++;
			 }
		}, 500);
		
	}

</script>



<?php endif; ?>