<?php
/**
 * WDCA - Sweet Tooth
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the WDCA SWEET TOOTH POINTS AND REWARDS 
 * License, which extends the Open Software License (OSL 3.0).
 * The Sweet Tooth License is available at this URL: 
 *      http://www.wdca.ca/solutions_page_sweettooth/Sweet_Tooth_License.php
 * The Open Software License is available at this URL: 
 *      http://opensource.org/licenses/osl-3.0.php
 * 
 * DISCLAIMER
 * 
 * By adding to, editing, or in any way modifying this code, WDCA is 
 * not held liable for any inconsistencies or abnormalities in the 
 * behaviour of this code. 
 * By adding to, editing, or in any way modifying this code, the Licensee
 * terminates any agreement of support offered by WDCA, outlined in the 
 * provided Sweet Tooth License. 
 * Upon discovery of modified code in the process of support, the Licensee 
 * is still held accountable for any and all billable time WDCA spent 
 * during the support process.
 * WDCA does not guarantee compatibility with any other framework extension. 
 * WDCA is not responsbile for any inconsistencies or abnormalities in the
 * behaviour of this code if caused by other framework extension.
 * If you did not receive a copy of the license, please send an email to 
 * contact@wdca.ca or call 1-888-699-WDCA(9322), so we can send you a copy 
 * immediately.
 * 
 * @category   [TBT]
 * @package    [TBT_Rewards]
 * @copyright  Copyright (c) 2009 Web Development Canada (http://www.wdca.ca)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

/**
 * Special Header
 *
 * @category   TBT
 * @package    TBT_Rewards
 * @author     WDCA Sweet Tooth Team <contact@wdca.ca>
 */
?>
<?php if($this->getPointsSummary() != ""): ?>
	<div class="points-special-header">
    	<a href="/index.php/rewards/customer/"><?php $pointssummary = $this->getPointsSummary();
        $header_points_balance = substr_replace($pointssummary,"",-7);
        echo $pointssummary; ?></a>
	</div>
<?php else: ?>
	<div class="points-special-header" style="width: 60px;">
		<a href="#">0 Points</a>
	</div>
<?php endif; ?>
	
    <div class="tooltip">
        <div class="nav-points">
        <p>Spend points instead of cash</p>
        <img src="<?php echo $this->getSkinUrl();?>images/points.jpg"/ width="44" height="41">
        <span class="nav-earn">Earn points wherever<br/>you see this logo</span>
        <span class="nav-spend">Spend points at checkout for big savings</span>
        <div><span class="nav-expl">&pound;10-off costs 1000 points</span><a href="/index.php/rewards/customer">View my points</a></div>
        </div>
    </div>
    <script>// What is $(document).ready ? See: http://flowplayer.org/tools/documentation/basics.html#document_ready
    jQuery(document).ready(function() {
        jQuery(".points-special-header").tooltip({
            offset: [25, 12],
			position: 'bottom center',
			relative: true,
            effect: 'slide'
            })
        ;});
    </script>
