<?php $websites = $this->getWebsites(); ?>
<?php if ($websites): ?>
<p class="switcher"><label for="website_switcher"><?php echo $this->__('Choose Website') ?>:</label>
<select name="website_switcher" id="website_switcher" onchange="return switchWebsite(this);">
<?php if ($this->hasDefaultOption()): ?>
    <option value=""><?php echo $this->getDefaultStoreName() ?></option>
<?php endif; ?>
    <?php foreach ($websites as $website): ?>
        <option value="<?php echo $website->getId() ?>"<?php if ($this->getStoreId() == $website->getId()): ?> selected="selected"<?php endif; ?>><?php echo $website->getName() ?></option>
    <?php endforeach; ?>
</select>
</p>
<script type="text/javascript">
    function switchWebsite(obj){
        var storeParam = obj.value ? 'website/'+obj.value + '/' : '';
        if(obj.switchParams){
            storeParam+= obj.switchParams;
        }
    <?php if($this->getUseConfirm()): ?>
        if(confirm("<?php echo $this->__('Please confirm site switching. All data that hasn\'t been saved will be lost.') ?>")){
            setLocation('<?php echo $this->getSwitchUrl() ?>'+storeParam);
            return true;
        }
        else {
            obj.value = '<?php echo $this->getStoreId() ?>';
        }
        return false;
    <?php else: ?>
        setLocation('<?php echo $this->getSwitchUrl() ?>'+storeParam);
    <?php endif; ?>
    }
</script>
<?php endif; ?>
