<?php
/**
 * Create account form template
 * Modified by Arush Oneall
 *
 * @see Mage_Customer_Block_Form_Register
 */
?>
<div class="black-title-bar"><?php echo $this->__('Looks like your email is already registered') ?></div>
<div class="account-login">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<div class="col2-set">
		
	
			<div class="col-1 registered-users">
				<span class="black-title-med"><span class="register-red-or"><?php echo $this->__('That\'s ok') ?></span><?php echo $this->__(' connect accounts now') ?></span>

				<div id="panes">
					
					
					<div id="slider">
						<?php /* ?><ul class="navigation">
							<li><a id="signin-button" href="#login">Members sign in</a></li>
							<li><a id="become-button" href="#register">Become a Member</a></li>
						</ul><?php */ ?>
							<!-- a id="become-member" href="http://www.evogue.co.uk/editorial/?page_id=120">Become a Member</a -->
					
						
					<!-- element with overflow applied -->
						<div class="scroll rpx-duplicate-scroll">
							<!-- the element that will be scrolled during the effect -->
							<div class="scrollContainer">
								<!-- our individual panels -->
															
								<div class="panel" id="login">
								
									<form action="<?php echo Mage::getUrl('oneall/rpx/loginpost') ?>" method="post" id="login-form">
											<div class="content">
												<ul class="form-list">
													<li>
														<label><span class="black-title-small"><?php echo $this->__('Email') ?></span></label>
														<div class="input-box" id="read-only-email">
															<strong><em><?php echo $this->htmlEscape($this->getUsername()) ?></em></strong>
														</div>
													</li>
													<li>
														<label for="pass" class="required"><span class="black-title-small"><em>*</em><?php echo $this->__('Password') ?></span></label>
														<div class="input-box">
															<input type="hidden" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
															<input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
														</div>
													</li>
												</ul>
											</div>
											<div class="buttons-set">
												<a href="#forgotpass" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
												<button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
											</div>
									</form>
								</div> <!-- end panel -->

								<div class="panel" id="forgotpass">
									<form action="<?php echo $this->getUrl('customer/account/forgotpasswordpost') ?>" onsubmit="return false" method="post" id="form-validate">
										<fieldset>
											<div class="field set">
													<ul class="form-list">
														<li>
															<label for="email_address" class="required"><span class="black-title-small"><?php echo $this->__('email') ?></span></label>
															<div class="input-box">
																<input type="text" name="email" alt="email" id="forgotpass_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
															</div>
														</li>
													</ul>
													<div class="forgotpass-buttons buttons-set form-buttons">
														<div class="forgotpass-back-link"><a href="#login"><?php echo $this->__('Go back') ?></a></div>

														<button type="submit" name="submit" class="button" id="submit_btn" value="Send"><span><span class="cufon"><?php echo $this->__('Reset Password') ?></span></span></button>
														
														<span id="forgotpass-response"></span>
													<div style="clear: both;"><!-- --></div>
													<span id="forgotpass-response"></span>

												</div>
											</div>
										</fieldset>
									</form>
								</div>
								
							</div> <!-- end scrollContainer -->
						</div> <!-- end scroll -->
					</div> <!-- end slider -->
				
				</div> <!-- end panes -->
			</div> <!-- end col1 -->

		
		<form action="<?php echo Mage::getUrl('oneall/rpx/createpost'); ?>" method="post" id="form-validate">
			<div class="col-2 new-users">
				<div class="content">
					<span class="black-title-med"><span class="register-red-or"><?php echo $this->__('…or') ?></span><?php echo $this->__(' use another email') ?></span>
					<ul class="form-list">
						<li>
							<label for="firstname" class="required"><span class="black-title-small"><em>*</em><?php echo $this->__('First Name') ?></span></label>
							<div class="input-box">
								<input type="text" name="firstname" value="<?php echo $this->htmlEscape($this->getFormData()->getFirstname()) ?>" id="firstname" class="input-text required-entry" title="<?php echo $this->__('First Name') ?>" />
							</div>
						</li>
						<li>
							<label for="lastname" class="required"><span class="black-title-small"><em>*</em><?php echo $this->__('Last Name') ?></span></label>
							<div class="input-box">
								<input type="text" name="lastname" value="<?php echo $this->htmlEscape($this->getFormData()->getLastname()) ?>" id="lastname" class="input-text required-entry" title="<?php echo $this->__('Last Name') ?>" />
							</div>
						</li>
						<li>
							<label for="email_address" class="required"><span class="black-title-small"><em>*</em><?php echo $this->__('Email') ?><span class="black-title-small"></label>
							<div class="input-box">
								<input type="text" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
								<?php
									$password = md5('Arush_Oneall_' .  Mage::helper('oneall')->rand_str(12));
								?>
								<input type="hidden" name="password" value="<?php echo $password; ?>" />
								<input type="hidden" name="confirmation" value="<?php echo $password; ?>" />
								<input type="hidden" name="success_url" value="<?php echo Mage::getSingleton('customer/session')->getBeforeAuthUrl(); ?>" />
							</div>
						</li>
					</ul>
					<p class="required"><?php echo $this->__('* Required Fields') ?></p>
				</div>
				<div class="buttons-set">
					<button type="submit" class="button" title="<?php echo $this->__('Submit') ?>" id="send"><span><span><?php echo $this->__('Submit') ?></span></span></button>
				</div>
			</div>
		</form>
	</div>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
    
    <script type="text/javascript">
    //<![CDATA[
		$('submit_btn').observe('click', function(){
		    
		    $('forgotpass-response').addClassName('loading');
			$('forgotpass-response').innerHTML = 'Resetting your password…';
		    
		    var ajax = this.form.request({
		        onSuccess: function(transport) {
		            if(transport.responseText.indexOf('customer-account-login') >= 0) {
          				$('forgotpass-response').removeClassName('loading');
						$('forgotpass-response').innerHTML="Done - check your email";
		            }
		            else if(transport.responseText.indexOf('Invalid email address.') >= 0) {
          				$('forgotpass-response').removeClassName('loading');
						$('forgotpass-response').innerHTML="Invalid email address";
		            }
		            else if(transport.responseText.indexOf('Please enter your email.') >= 0) {
          				$('forgotpass-response').removeClassName('loading');
						$('forgotpass-response').innerHTML="Please enter an email address";
		            }
		            else {
		            
          				$('forgotpass-response').removeClassName('loading');
						$('forgotpass-response').innerHTML="Address not found";
		            }


		            
		        }
		    });
		    Event.stop();
		});
    //]]>
    </script>

    
</div>