<?php
if (Mage::helper('oneall')->isOneallEnabled()):
?>

<script type="text/javascript">
	var oneall_js_protocol = (("https:" == document.location.protocol) ? "https" : "http");
	document.write(unescape("%3Cscript src='" + oneall_js_protocol + "://<?php echo Mage::getStoreConfig('oneall/options/apidomain') ?>.api.oneall.com/socialize/library.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<?php
endif; ?>