<!-- The plugin will be embedded into this div //-->

<div class="social-link info-box">
<div class="black-title-bar">Connect your social accounts</div>
<div id="social_link_container" class="loading"></div>
<script type="text/javascript">
 oneall.api.plugins.social_link.build("social_link_container", {
  'providers' :  ['facebook', 'google','twitter', 'yahoo'], 
  'user_token': '<?php echo Mage::getModel('customer/customer')->load(Mage::getSingleton('customer/session')->getId())->getOneallUserToken(); ?>',
  'css_theme_uri': '<?php echo $this->getSkinUrl(); ?>css/social_link.css',
  'grid_size_x': '2',
  'callback_uri': '<?php echo Mage::getUrl('', array('_nosid' => true, '_forced_secure' => true)); ?>arush-oneall/rpx/token_url_add/',
  'events' :{
        'onload' : function(){jQuery('#social_link_container').removeClass('loading');}   
      } 
 });
</script>

</div>