<?php
    	$today = time();
    	$nextDrop = mktime(0,0,0,date('m')+1,Mage::getStoreConfig('randomquote/general/delivery_date'), date('Y'));
    	//$drop = split('-', date('d-h-m-s', $nextDrop-$today));
		$drop = explode('-', date('d-h-m-s', $nextDrop-$today));
?>
<div class="countdown-subscription">
	<div class="countdown">
		<div class="title"><span><?php echo $this->getTitle(); ?></span></div>
		<div class="content">
			<div class="counter">
				<ul>
					<li><?php echo $this->__('Days'); ?></li>
					<li><?php echo $this->__('Hours'); ?></li>
					<li><?php echo $this->__('Minutes'); ?></li>
					<li><?php echo $this->__('Seconds'); ?></li>												
				</ul>
				<ul class="flip-counter-ul">
					<li><div id="countdownDays" class="flip-counter"></div></li>
					<li><div id="countdownHours" class="flip-counter"></div></li>
					<li><div id="countdownMinutes" class="flip-counter"></div></li>
					<li class="last"><div id="countdownSeconds" class="flip-counter"></div></li>												
				</ul>			
				
			</div>
		</div>
		<div class="text"><span><?php echo $this->getContent();?></span></div>
		
	</div>
</div>

<script type="text/javascript">

	var nextDrop = <?php echo $nextDrop-$today; ?>;
	var lastDate = new Date(<?php echo $nextDrop-$today; ?>);
	var countdownDays = new flipCounter('countdownDays', {value:0, inc:3, pace:15, tFH: 20, bFH: 34, fW: 28, bOffset: 200});
	countdownDays.incrementTo(0);				
	
	var countdownHours = new flipCounter('countdownHours', {value:0, inc:3, pace:15, tFH: 20, bFH: 34, fW: 28, bOffset: 200});
	countdownHours.incrementTo(0);				
	
	var countdownMinutes = new flipCounter('countdownMinutes', {value:0, inc:3, pace:15, tFH: 20, bFH: 34, fW: 28, bOffset: 200});
	countdownMinutes.incrementTo(0);				
	
	var countdownSeconds = new flipCounter('countdownSeconds', {value:0, inc:3, pace:15, tFH: 20, bFH: 34, fW: 28, bOffset: 200});	
	countdownSeconds.incrementTo(0);				
						

	function runDays(inc) {
		countdownDays.incrementTo(inc);				
	}

	function runHours(inc) {
		countdownHours.incrementTo(inc);				
	}

	function runMinutes(inc) {
		countdownMinutes.incrementTo(inc);				
	}

	function runSeconds(inc) {
		countdownSeconds.incrementTo(inc);				
	}

	function startTimer() {

		if (nextDrop < 0) { return; }
		nextDrop -= 1000;
		var datePieces = new Date(nextDrop);

		if (datePieces.getDate() != lastDate.getDate()) { runDays(datePieces.getDate()); }
		if (datePieces.getHours() != lastDate.getHours()) { runHours(datePieces.getHours()); }
		if (datePieces.getMinutes() != lastDate.getMinutes()) { runMinutes(datePieces.getMinutes()); }
		if (datePieces.getSeconds() != lastDate.getSeconds()) { runSeconds(datePieces.getSeconds()); }		
		lastDate = datePieces;
	}

	function fixFloats() {
		$$('.flip-counter-ul div').each(function(obj){
		 if (obj.select('ul').length > 1) {
		 	obj.select('ul').each(function(o){
		 		o.setStyle({ float: 'left' });
		 	});
		 } else {
		 	obj.select('ul').each(function(o){
		 		o.setStyle({ float: 'right' });
		 	});		 
		 }
		});
	}

	document.observe('dom:loaded', function(){
		setInterval('fixFloats()', 50);	
//		runSeconds(<?php echo $drop[0]; ?>);
		setTimeout('runDays(<?php echo $drop[0]; ?>)', 200);		
		setTimeout('runMinutes(<?php echo $drop[1]; ?>)', 400);		
		setTimeout('runHours(<?php echo $drop[2]; ?>)', 600);		
		setInterval('startTimer()', 1000);
	});	
</script>