<?php $_quote = $this->getQuote(); ?>

<div class="footer quote-footer">
	<div class="footer-container">
	
		<div class="random-quote">
			<span class="apostrophe">"</span>
			<span class="quote"><?php echo $this->__($_quote['quote']);?></span>
			<div class="quote-triangle"></div>
			<span class="author"><?php echo $this->__($_quote['author']);?></span>
			<span class="caption"><?php echo $this->__($_quote['caption']);?></span>
		</div>

	</div>
</div>