
<div class="my-points">
	<h1 class="black-title-bar"><?php echo $this->__('My points'); ?></h1>
	<div class="content">
		
		
		<div class="points-triangle-container">
			<a id="earn" href="/rewardsref/customer/index/"><?php echo $this->__('Earn more'); ?></a>
		</div>

		<div class="points-triangle">
		</div>


		
		<div id="my-points" class="flip-counter"></div><span><?php echo $this->__('points'); ?></span><br />

		<span class="info"><?php echo $this->getText(); ?></span>
		<?php
		
		if($this->getPoints() > 1000) {
				$startValue = $this->getPoints() - 100;
			}
			else if($this->getPoints() > 0){
				$startValue = (int)($this->getPoints()-($this->getPoints()/10));
			}
			else { // points balance = 0
				$startValue = 100;
			}

		?>
		<script type="text/javascript">
			document.observe('dom:loaded', function(){
				var myCounter = new flipCounter('my-points', {value:<?php echo $startValue; ?>, inc:3, pace:30, tFH: 20, bFH: 34, fW: 28, bOffset: 200});
					myCounter.incrementTo(<?php echo $this->getPoints(); ?>);				
			});	
		</script>
	</div>
	
</div>