<?php $products = $this->getCollection(); ?>
<?php if ($products->count() > 0): ?>
<div class="sliders quickie">
	<div class="sliders-footer-container quickie">
	
		<span class="black-title-med"><?php echo $this->__('Fancy a Quickie');?></span>	
		<div class="holder">
		
			<div class="slider">
				<ul>
				<?php foreach($products as $product): ?>
					<li>
						<img src="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize(132, 163);?>" width="132" height="163" />
						<!-- span class="black-title-small"><?php // echo $product->getAttributeText('brand'); ?></span-->
						<!-- span><?php // echo Mage::helper('core')->currency($product->getPrice(), true); ?></span-->
					</li>
				<?php endforeach; ?>
				</ul>
			</div>
			<div class="left"></div>		
			<div class="right"></div>	
		</div>
	</div>
</div>
<?php endif; ?>