
<?php
$products = $this->getCollection();
if ($products->count() > 0):
?>
<div class="relationship">
	<span class="black-title-med"><?php echo $this->__('How about a steady relationship?'); ?></span>
	<ul class="relationship">
	<?php $counter=0;foreach($products as $product): ?>
		<?php $counter++; $lastClass = ($counter % 3 == 0) ? ' class="last"' : ''; ?>
		
		<li<?php echo $lastClass?>>
			<h3><? echo $product->getName(); ?></h3>
			<span class="price">RRP &pound;<?php echo number_format($product->getPrice(), 0)?></span><br />
			<span class="special-price">&pound;<?php echo number_format($product->getSpecialPrice(), 0)?></span>
			<a href="<?php echo $product->getProductUrl() ?>"><?php echo $this->__('View plan'); ?></a>
		</li>
	<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>