<?php
/**
 * WDCA - Sweet Tooth
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the WDCA SWEET TOOTH POINTS AND REWARDS 
 * License, which extends the Open Software License (OSL 3.0).
 * The Sweet Tooth License is available at this URL: 
 *      http://www.wdca.ca/solutions_page_sweettooth/Sweet_Tooth_License.php
 * The Open Software License is available at this URL: 
 *      http://opensource.org/licenses/osl-3.0.php
 * 
 * DISCLAIMER
 * 
 * By adding to, editing, or in any way modifying this code, WDCA is 
 * not held liable for any inconsistencies or abnormalities in the 
 * behaviour of this code. 
 * By adding to, editing, or in any way modifying this code, the Licensee
 * terminates any agreement of support offered by WDCA, outlined in the 
 * provided Sweet Tooth License. 
 * Upon discovery of modified code in the process of support, the Licensee 
 * is still held accountable for any and all billable time WDCA spent 
 * during the support process.
 * WDCA does not guarantee compatibility with any other framework extension. 
 * WDCA is not responsbile for any inconsistencies or abnormalities in the
 * behaviour of this code if caused by other framework extension.
 * If you did not receive a copy of the license, please send an email to 
 * contact@wdca.ca or call 1-888-699-WDCA(9322), so we can send you a copy 
 * immediately.
 * 
 * @category   [TBT]
 * @package    [TBT_Rewards]
 * @copyright  Copyright (c) 2009 Web Development Canada (http://www.wdca.ca)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

/**
 * Customer SideBar
 *
 * @category   TBT
 * @package    TBT_Rewards
 * @author     WDCA Sweet Tooth Team <contact@wdca.ca>
 */
?>
<div class="rewards-sidebar">
    <div class="page-title black-title-bar">
		<?php echo $this->__('Points Balance') ?>
    </div>
    
    <div class="content block-content">
    		<?php if($this->isCustomerLoggedIn()): ?>        		
        		<div class="balance">        		
	        		<?php echo $this->__('You have %s to spend.', $this->getCustomerPoints()) ?>
        		</div>  			
    		<?php endif; ?>
    <div class="actions">
    	<a href="<?php echo $this->getUrl('rewards/customer') ?>">
    		<?php if($this->isCustomerLoggedIn()): ?>
    			<?php echo $this->__('View My Activity') ?><br/><br/><br/>
    			
    		<?php else: ?>
    			<?php echo $this->__('Log-in or create a new account') ?>
    		<?php endif; ?>
    		<a href="<?php echo $this->getUrl('rewardsref/customer/index') ?>"><?php echo $this->__('Earn more points now') ?></a>
    	</a>
    </div>
    </div>
    
    	
</div>