<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <li>
        <div class="input-box">
            <label for="repeatpaymentcode"><?php echo Mage::helper('sagepaysuite')->__('Transaction ID (VPS TX ID)') ?> <span class="required">*</span></label><br/>
            <input type="text" id="repeatpaymentcode" name="payment[repeat_code]" title="<?php echo Mage::helper('sagepaysuite')->__('Please enter VPSTxId'); ?>" class="required-entry input-text" value="<?php echo $this->getInfoData('repeat_code') ?>"/>
            &nbsp;<?php echo $this->getSearchButtonHtml(); ?>
            <input type="hidden" value="<?php echo $this->getSearchGridUrl(); ?>" id="sagepayrepeat-search-url" />
        </div>
    </li>
</ul>