	<?php

?>


<div class="header-container">
    <div class="header">
	
		<div class="top-header">
			<!-- div class="store-language"><?php // echo $this->getChildHtml('store_language') ?></div-->
			<!-- div class="facebook-header"><?php // echo $this->getLayout()->createBlock('cms/block')->setBlockId('header-fb-like')->toHtml() ?></div-->
			<?php /* echo $this->getChildHtml('topLinks') */ ?>
		    
			<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) {?>
				<div class="top-name">
					
					<!--oneall thumbnail -->
					<?php // TODO put this in the module code
					
					$customerID = Mage::getSingleton('customer/session')->getId();
					//check if user has a Facebook ID or twitter ID
					$model = Mage::getModel('oneall/identifiers');
					$collection = $model->getCollection()
						->addFieldToFilter('customer_id',$customerID)
						->addFieldToFilter('provider',array('in' => array('facebook','twitter')));
					foreach($collection as $item) {
					   if($item['provider'] === 'facebook') {
			   				$facebookID = $item['identifier'];
			   			}
			   			else if($item['provider'] === 'twitter') {
			   				$twitterID = $item['profile_name'];
			   			};
					   
					}
					
					
					if(isset($facebookID)) { ?>
						<img class="oaimg" width="50" height="50" src="https://graph.facebook.com/<?php echo $facebookID ?>/picture?type=square" />
					<?php  } else if(isset($twitterID)) { ?>
						<img class="oaimg" width="50" height="50" src="https://api.twitter.com/1/users/profile_image?screen_name=<?php echo $twitterID ?>&size=normal" />
					<?php
					} else {
					?><style type"text/css">.top-header .account-link a.header-link { padding-right:0px; }</style><?php
					}
					?>
					
					<?php // Mage::helper('oneall')->getThumbnailUrl(); ?>
					<!--oneall thumbnail -->
					


				</div>

				<div class="account-link">
					<a class="header-link" href="/customer/account/index/">My Account</a>
					<?php $customerName = Mage::helper('customer')->getCustomerName(); 
						$names = explode(" ",$customerName, 2);
						$firstname = $names[0];
					
					?> 						
					<a class="flname" href="#">Hi <?php echo $firstname; ?></a>						
					<div class="my-account-links">
						<?php echo $this->getChildHtml('accountLinks') ?>
					</div>					
				
				</div>
				
				<script>
					jQuery(document).ready(function () { 
		 
						jQuery('.account-link').hover(
							function () {
								//show its submenu
								jQuery('.my-account-links').slideDown(100);
					 
							}, 
							function () {
								//hide its submenu
								jQuery('.my-account-links').slideUp(100);         
							}
						);
									jQuery('.account-link').hover(
										function() {
										  jQuery(this).addClass('light');
											},
										function() {
										  jQuery(this).removeClass('light');
									});
					});
				</script>
			<?php }; ?>
	
				<?php  echo $this->getChildHtml('topCart') ?>

			<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) { ?>
				<div id="nav-invite">
				
					<a class="header-link" href="/index.php/rewardsref/customer/index/">Invite and earn</a>
				<?php /*WDCA CODE BEGIN*/ ?>
				<?php echo $this->getChildHtml('rewardsHeader') ?>
				<?php /*WDCA CODE END*/ ?>					
				
				</div>
			<?php }; ?>

			<div class="catalogLinks"><?php echo $this->getChildHtml('catalogLinks') ?></div>
			
			<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
				<div class="not-logged-in-header">
					<div class="login-register-header">
						<div class="login-header">
							<?php echo $this->getChildHtml('accountLinks') ?>
						</div>
						<div class="register-header">
							<a href="/customer/account/create">Register</a>
						</div>
					</div>				

						<!-- The provider login will be embedded in this div //-->
						<div class="connect">or connect</div>
						<div id="oa_social_login_header"></div>
						<script type="text/javascript">
							 oneall.api.plugins.social_login.build("oa_social_login_header", {
							  'providers' :  ['facebook', 'google', 'twitter', 'yahoo'], 
							  'callback_uri': '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>arush-oneall/rpx/token_url/',
							  'css_theme_uri': '<?php echo $this->getSkinUrl(); ?>css/brandid.css'
							 });
						</script>	
				</div>
				
			<?php endif; ?>

		<div class="branding">
        <?php if ($this->getIsHomePage()):?>
            <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
            <?php else:?>
            <a href="/plans.html<?php // echo $this->getUrl('p') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif?>
        </div>	   			
			
		</div>	
		 
		<?php //echo $this->getChildHtml('topMenu') ?>
    </div>
    
    
</div>

