<div class="page-title">
    <h1><?php echo $this->__('Newsletter Subscription') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
<div class="fieldset">
    <?php echo $this->getBlockHtml('formkey')?>
    <ul class="form-list">
        <li class="control">
            <label for="subscription"><?php echo $this->__('General Subscription') ?></label>
            <div class="input-box">
                <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
            </div>
        </li>
    </ul>
</div>
<div class="buttons-set form-buttons">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Go back') ?></a></p>
    <button type="submit" class="button" title="<?php echo $this->__('Save') ?>"><span><span><?php echo $this->__('Save') ?></span></span></button>
</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
