<script type="text/javascript" charset="utf-8">
  var refreshIntervalId;  
  jQuery(function(){
    
      jQuery("#expires").each(function(){
        var vals;
        
        if(UTCDate) {
          function refreshdate(){
            vals = jQuery.date.timeSince(UTCDate);
            updateDateVals(vals);
          }
          //run the countdown thing
          UTCDate = parseDate(UTCDate);
          //UTCDate = jQuery.date.addDays(UTCDate, 1);
          refreshIntervalId = setInterval(refreshdate, 1000);
        }
      });
    });
    
    function parseDate(str) {
      var v=str.split(' ');
      return new Date(Date.parse(v[1]+" "+v[2]+", "+v[5]+" "+v[3]+" UTC"+v[4]));
    }
    
    function updateDateVals(vals){
      if(vals[0]<0 && vals[1]<0 && vals[2]<0 && vals[3]<0) {
              clearInterval(refreshIntervalId);
              jQuery("#expires .dys").text(00);
              jQuery("#expires .hrs").text(00);
              jQuery("#expires .min").text(00);
              jQuery("#expires .sec").text(00);
            }
      else{
        jQuery("#expires .dys").text(vals[0]);
        jQuery("#expires .hrs").text(vals[1]);
        jQuery("#expires .min").text(vals[2]);
        jQuery("#expires .sec").text(vals[3]);
      }
    }
  </script>

<?php

  $countdown = $this->getCountdownTo();

?>
<script type="text/javascript" charset="utf-8">
  var UTCDate = "<?php echo $countdown; ?>";
</script>

