<?php

  
  if (!file_exists(".htaccess.sonassi.bak"))
    file_put_contents(".htaccess.sonassi.bak",file_get_contents(".htaccess"));   
    
  if (!file_exists("../.htaccess.sonassi.bak"))
    file_put_contents("../.htaccess.sonassi.bak",file_get_contents("../.htaccess"));       

  $ip = file_get_contents("http://ip.sonassi.com");
  $ip = trim(str_replace(".","\.",$ip));
  
  $identifier = "sonassi.com wordpress extension";
  $match = "RewriteCond %{REMOTE_ADDR} !^";
  
  $cur_htaccess = file_get_contents(".htaccess");
  if (strpos($cur_htaccess, "# BEGIN WordPress") === false) {
    
    $htaccess = "
# BEGIN WordPress

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . index.php [L]
</IfModule>

# END WordPress        
    ";
  
    file_put_contents(".htaccess",$htaccess);
    echo ".htaccess generated";      
      
  }       
  
  $cur_htaccess = (file_exists(".htaccess")) ? file_get_contents(".htaccess") : "";
  
  if (strpos($cur_htaccess,"## BEGIN $identifier") !== false) {
  
    $start_point = strpos($cur_htaccess,"## BEGIN $identifier");
    $end_point = strpos($cur_htaccess,"## END $identifier");
    
    $sonassi_htaccess_chunk = substr($cur_htaccess,$start_point,$end_point+strlen("## END $identifier")-$start_point);  
    
    $cur_ip = substr($cur_htaccess,strpos($cur_htaccess,$match)+strlen($match));
    $cur_ip = trim(substr($cur_ip,0,strpos($cur_ip,"RewriteRule")));
    
    if ($cur_ip != $ip) {
      echo "IP mismatch in .htaccess<br />";
      $new_sonassi_htaccess_chunk = str_replace($cur_ip,$ip,$sonassi_htaccess_chunk);
      $new_htaccess = str_replace($sonassi_htaccess_chunk,$new_sonassi_htaccess_chunk,$cur_htaccess);
      file_put_contents(".htaccess",$new_htaccess);
      echo ".htaccess generated";    
    }
  } elseif(strpos($cur_htaccess,"## BEGIN $identifier") === false) {
    echo "Missing sonassi_wordpress code in .htaccess<br />";
  
    $htaccess = "
# autogenerated by {$_SERVER['SCRIPT_NAME']} 

## BEGIN $identifier
  
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /blog/

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_URI} !^/blog/wp-admin
RewriteCond %{REQUEST_URI} !^/blog/wp-content
RewriteCond %{REQUEST_URI} ^/blog
RewriteCond %{REMOTE_ADDR} !^$ip
RewriteRule .* ../index.php [L]
</IfModule>

## END $identifier
    ";
    
    file_put_contents(".htaccess",$htaccess.file_get_contents(".htaccess"));
    echo ".htaccess generated";
    
  }
    
  $cur_htaccess = (file_exists("../.htaccess")) ? file_get_contents("../.htaccess") : "";
  
  $sonassi_htaccess = "
############################################
## BEGIN $identifier
##
 
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_URI} !^/blog/wp-admin
    RewriteCond %{REQUEST_URI} !^/blog/wp-content 		
    RewriteCond %{REQUEST_URI} ^/blog
    RewriteCond %{REMOTE_ADDR} !^$ip
    RewriteRule .* index.php [L] 

## END $identifier
    \r\n";  
  
  if (strpos($cur_htaccess,$identifier) === false) {
    echo "Missing sonassi_wordpress code in ../.htaccess<br />";
   
    $insert_point = strpos($cur_htaccess,"RewriteBase");
    $temp_htaccess = substr($cur_htaccess,$insert_point);
    $start_htaccess = substr($cur_htaccess,0,strpos($temp_htaccess,"#######")+$insert_point);
       
    $new_htaccess = str_replace($start_htaccess,$start_htaccess.$sonassi_htaccess,$cur_htaccess);
    
    file_put_contents("../.htaccess",$new_htaccess);
    echo ".htaccess generated";   
  } elseif ((strpos($cur_htaccess,$identifier) !== false)) {  
    $start_point = strpos($cur_htaccess,"## BEGIN $identifier");
    $end_point = strpos($cur_htaccess,"## END $identifier");
    
    $sonassi_htaccess_chunk = substr($cur_htaccess,$start_point,$end_point+strlen("## END $identifier")-$start_point);
    
    $cur_ip = substr($sonassi_htaccess_chunk,strpos($sonassi_htaccess_chunk,$match)+strlen($match));
    $cur_ip = trim(substr($cur_ip,0,strpos($cur_ip,"RewriteRule")));
    
    if ($cur_ip != $ip || strpos($cur_htaccess,$identifier) === false) {
      echo "IP mismatch in ../.htaccess<br />";      
      $new_sonassi_htaccess_chunk = str_replace($cur_ip,$ip,$sonassi_htaccess_chunk);
      $new_htaccess = str_replace($sonassi_htaccess_chunk,$new_sonassi_htaccess_chunk,$cur_htaccess);
      file_put_contents("../.htaccess",$new_htaccess);
      echo ".htaccess generated";
    }
  }

?>