<?php
    if($this->getParentBlock()->getInfo()->getOrder()->getSagepayInfo()->getTxType() != Ebizmarts_SagePaySuite_Model_Api_Payment::REQUEST_TYPE_AUTHENTICATE){
        return;
    }

    $authorises = $this->getParentBlock()->getAuthorisesCollection();

    if($authorises->getSize()):
?>
<div class="grid" id="sagepay-authorises-table">
    <?php echo $this->__('<strong>AUTHORISE</strong>s'); ?>
    <table class="data" cellspacing="0">
        <thead>
            <tr class="headings">
                <th><?php echo $this->__('Status'); ?></th>
                <th><?php echo $this->__('Amount'); ?></th>
                <th><?php echo $this->__('VPS Tx Id'); ?></th>
                <th><?php echo $this->__('Auth No'); ?></th>
                <th><?php echo $this->__('Date'); ?></th>
            </tr>
        </thead>
        <tbody class="even">
            <?php foreach($authorises as $_authorise): ?>
            <tr class="border">
                <td><?php echo $_authorise->getStatus(); ?></td>
                <td><?php echo $this->helper('core')->currency($_authorise->getAmount()); ?></td>
                <td><?php echo $this->getParentBlock()->detailLink($_authorise->getVpsTxId()); ?></td>
                <td><?php echo $_authorise->getTxAuthNo(); ?></td>
                <td><?php echo $this->formatDate(new Zend_Date(strtotime($_authorise->getActionDate())), 'short', true); ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>
