<?php

    $repeats = $this->getParentBlock()->getRepeatsCollection();

    if($repeats->getSize()):
?>
<div class="grid" id="sagepay-repeats-table">
    <?php echo $this->__('<strong>REPEAT</strong>s'); ?>
    <table class="data" cellspacing="0">
        <thead>
            <tr class="headings">
                <th><?php echo $this->__('Status'); ?></th>
                <th><?php echo $this->__('Amount'); ?></th>
                <th><?php echo $this->__('VPS Tx Id'); ?></th>
                <th><?php echo $this->__('Auth No'); ?></th>
                <th><?php echo $this->__('Date'); ?></th>
            </tr>
        </thead>
        <tbody class="even">
            <?php foreach($repeats as $rpt): ?>
            <tr class="border">
                <td><?php echo $rpt->getStatus(); ?></td>
                <td><?php echo $this->helper('core')->currency($rpt->getAmount()); ?></td>
                <td><?php echo $this->getParentBlock()->detailLink($rpt->getVpsTxId()); ?></td>
                <td><?php echo $rpt->getTxAuthNo(); ?></td>
                <td><?php echo $this->formatDate(new Zend_Date(strtotime($rpt->getActionDate())), 'short', true); ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>