<div class="dashboard">
<div class="page-title">
    <h4><?php echo $this->__('My Dashboard') ?></h4>
</div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php // echo $this->getChildHtml('hello') ?>
    
    <?php /*WDCA CODE BEGINS ?>
    <?php if(!Mage::getStoreConfigFlag('advanced/modules_disable_output/TBT_Rewards') 
        	&& Mage::getConfig()->getModuleConfig('TBT_Rewards')->is('active', 'true')) : ?>
    <?php echo Mage::getBlockSingleton('rewards/customer_summary')->toHtml()?>
    <?php endif;?>
    <?php /*WDCA CODE ENDS*/?>
    
    <?php echo $this->getChildHtml('top') ?>
    <?php echo $this->getChildHtml('info') ?>
    <?php echo $this->getChildHtml('address') ?>
    <?php echo $this->getChildHtml('info1') ?>
    <?php echo $this->getChildHtml('info2') ?>
</div>