<?php
/**
 * Manufacturers extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    Manufacturers
 * @author     Kamran Rafiq Malik <kamran.malik@unitedsol.net>
 * @copyright  Copyright 2010 © free-magentoextensions.com All right reserved
 */
?>
<?php
$config = Mage::getModel('manufacturers/image_config');
$image = Mage::getModel('media/image');
$image->setConfig($config);	
?>
<?php $collection = $this->getAllLeftManufacturers(); ?>
<?php if ( count($collection) != 0 ) : ?>
<div class="block block-layered-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Shop By') ?></span></strong>
    </div>
    <div class="block-content">
        <dl id="narrow-by-list2">
            <dt><?php echo $this->__(Mage::helper('manufacturers')->getMainHeadingText()) ?></dt>
            <dd style="margin-top:6px;">
                <ol>
                <?php $i=0; foreach ( $collection as $_manufacturer ) : ?>
					<?php 	$mcollection = Mage::getModel('manufacturers/manufacturers')->getProductsCount($_manufacturer['manufacturers_id'])->getData(); 
							$mcount = $mcollection[0]["products_count"];
					?>
                    <li>
                        <a class="image" href="<?php echo Mage::helper('manufacturers')->getUrl($_manufacturer['identifier']); ?>" title="<?php echo $_manufacturer["m_name"]; ?>">
						<?php echo $this->htmlEscape($_manufacturer["m_name"]) ?> (<?php echo $mcount; ?>)
                        </a>
                    </li>
                <?php endforeach ?>
                </ol>
            </dd>
        </dl>
        <script type="text/javascript">decorateDataList('narrow-by-list2')</script>
    </div>
</div>
<?php endif; ?>
