<?php
/**
 * Manufacturers extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    Manufacturers
 * @author     Kamran Rafiq Malik <kamran.malik@unitedsol.net>
 * @copyright  Copyright 2010 © free-magentoextensions.com All right reserved
 */
?>

<?php
$selected  = $this->getRequest()->getParam('start');
$typed  = $this->getRequest()->getParam('type');
$selectedClass = '';
$show_view_by = Mage::helper('manufacturers')->getShowViewBy();
$showLogo = Mage::helper('manufacturers')->getShowLogo();
$showAlphaHeading = Mage::helper('manufacturers')->getShowAlphaHeading();

if($typed=="text"){
	$showLogo = 0;
}elseif($typed=="logo"){
	$showLogo = 1;
}

?>

<div class="page-title category-title">
        <h1><?php echo $this->__(Mage::helper('manufacturers')->getMainHeadingText()); ?></h1>
</div>

<div class="manufacturer_sort">
	<?php if($show_view_by){ ?>
    <ol class="brandListView">
		<li class="brandListViewBy"><?php echo $this->__("View By"); ?></li>
		<li><a href="<?php echo Mage::helper('manufacturers')->getUrl();?>?type=text"<?php if($typed=='text' || $showLogo==0){?> class="current"<?php } ?>><span class="brandListTextview"></span><?php echo $this->__("Text"); ?></a></li>
		<li><a href="<?php echo Mage::helper('manufacturers')->getUrl();?>?type=logo"<?php if($typed=='logo' || $showLogo==1){?> class="current"<?php } ?>><span class="brandListIconview"></span><?php echo $this->__("Logo"); ?></a></li>
	</ol>
	<?php } ?>
	<ul id="manufacturer_char_filter">
        <li><a href="<?php echo Mage::helper('manufacturers')->getUrl(); ?>">All</a></li>
        <?php for ($i=65; $i<=90; $i++) { ?>
        <?php if(chr($i) == $selected) { 
        		$selectedClass = 'selected';
        	  } else { 
        		$selectedClass = '';
         	  } 
		?>
        <li class="<?php echo $selectedClass; ?>"><a href="<?php echo Mage::helper('manufacturers')->getUrl();?>?start=<?php echo chr($i);?>"><?php echo chr($i); ?></a></li>
    	<?php } ?>
    </ul>
</div>
<?php
	//Number of Manufacturers in one row
	$logoWidth = Mage::helper('manufacturers')->getLogoWidth();  
	$pageLayout = Mage::getStoreConfig('manufacturers/manufacturers/layout');
	if($pageLayout == "page/1column.phtml") {
		$contentWidth = 900;
		$_columnCount = floor($contentWidth/$logoWidth);
	} elseif($pageLayout == "page/2columns-right.phtml") {
		$contentWidth = 685;
		$_columnCount = floor($contentWidth/$logoWidth);
	} elseif($pageLayout == "page/2columns-left.phtml") {
		$contentWidth = 685;
		$_columnCount = floor($contentWidth/$logoWidth);
	} elseif($pageLayout == "page/3columns.phtml") {
		$contentWidth = 475;
		$_columnCount = floor($contentWidth/$logoWidth);
	} else {
		$contentWidth = 685;
		$_columnCount = floor($contentWidth/$logoWidth);
	}

?>
<?php
if($showLogo) {
?>
<div class="product_container">
<?php $_productCollection=$this->getItems(); ?>
<?php $_collectionSize = $_productCollection->count() ?>
	<?php if ( count($_productCollection) == 0 ) : ?>
		<p class="text_1"><?php echo $this->__('No '.Mage::helper('manufacturers')->getMainHeadingText().' found!'); ?></p>
	<?php else : ?>
    	 <div class="row_main">
        <?php $_collectionSize = count($_productCollection); ?>

        <?php $_columnCount = floor($_columnCount); $prev_row = "";?>
		<?php $i=1; foreach ( $_productCollection as $_product ) : ?> 	
        <?php  

			$x = Mage::helper('manufacturers')->getLogoWidth();  
        	$y = Mage::helper('manufacturers')->getLogoHeight(); 
			$color = Mage::helper('manufacturers')->getLogoBackgroundColor();
				
			if($_product["m_logo"] != "") {
				$imgPath = Mage::helper('manufacturers')->getResizedUrl($_product["m_logo"],$x,$y,$color);	
			} else {			
				$imageFile =  "manufacturers/files/n/i/no_image_available.jpg";
				$imgPath = Mage::helper('manufacturers')->getResizedUrl($imageFile,$x,$y,$color);
			}
			$letter = strtoupper(substr($_product["m_name"],0,1));
			if($showAlphaHeading){
				if ($letter != $prev_row) {
					echo "</div>
					<br style='clear:both;' /><br />
					<div class='row_main'><div class='letter_heading'>$letter</div><br />";
				}
			}
		?>	
    				<div class="casestudies">
                    	<div class="casestudy">
                        		  <a class="image" href="<?php echo Mage::helper('manufacturers')->getUrl($_product['identifier']); ?>" title="<?php echo $_product["m_name"]; ?>">
                                  	<img src="<?php echo $imgPath ?>" alt="<?php echo $_product["m_name"]; ?>">
                                  </a>
                                  <div class="window_content video" id="rbird_video" style="display: none;"></div>
                                  <div class="who">
                                    <h3><?php echo $this->htmlEscape($_product["m_name"]) ?></h3>
                                  </div>
                        </div>
                	</div>
              
             <?php if($i % $_columnCount == 0): ?>
             	</div>
                <br  style="clear:both;" /><br />
                <div class="row_main">
             <?php endif ?>
             <?php 
			 if(!$showAlphaHeading){
			 	$i++;
			 }else{
			 	$prev_row = $letter;
			 }
			 ?>            
  		<?php endforeach; ?>
</div>      
<br style="clear:both;" />
<?php /* Pagination control */ ?>
<?php if ( $_productCollection instanceof Zend_Paginator ) : ?>
<?php echo $this->getChildHtml('pagination'); ?>
<?php endif; ?>
<?php echo $this->getChildHtml('toolbar'); ?>
<?php endif; ?>
</div>

<?php } else { ?>
<div class="product_container">
<?php $_productCollection=$this->getItems(); ?>
<?php $_collectionSize = $_productCollection->count(); ?>
	<?php if ( count($_productCollection) == 0 ) : ?>
		<p class="text_1"><?php echo $this->__('No '.Mage::helper('manufacturers')->getMainHeadingText().' found!'); ?></p>
	<?php else : ?>
    	<div id="ul_manuf">
		<ul>
        	<?php $_collectionSize = count($_productCollection); ?>
			<?php $_columnCount = $_columnCount; $prev_row = ""; ?>
            <?php $i=1; foreach ( $_productCollection as $_product ) : ?>
            	<?php
					if($showAlphaHeading){
						$letter = strtoupper(substr($_product["m_name"],0,1));
						if ($letter != $prev_row) {
						echo "<li class='letter_heading'>$letter</li>";
						}
					}
				?>
				<li><a href="<?php echo Mage::helper('manufacturers')->getUrl($_product['identifier']); ?>"><?php echo $this->htmlEscape($_product["m_name"]) ?></a></li>
            <?php if($showAlphaHeading){$prev_row = $letter;} endforeach; ?>
        </ul>
        </div>
        <br style="clear:both;" />
        <?php /* Pagination control */ ?>
        <?php if ( $_productCollection instanceof Zend_Paginator ) : ?>
        <?php echo $this->getChildHtml('pagination'); ?>
        <?php endif; ?>
        <?php echo $this->getChildHtml('toolbar'); ?>
        <?php endif; ?>
</div>

<?php } ?>
