<?php
/**
 * WDCA - Sweet Tooth Instore
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the SWEET TOOTH (TM) INSTORE
 * License, which extends the Open Software License (OSL 3.0).
 * The Sweet Tooth Instore License is available at this URL: 
 * http://www.sweettoothrewards.com/instore/sweet_tooth_instore_license.txt
 * The Open Software License is available at this URL: 
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * DISCLAIMER
 * 
 * By adding to, editing, or in any way modifying this code, WDCA is 
 * not held liable for any inconsistencies or abnormalities in the 
 * behaviour of this code. 
 * By adding to, editing, or in any way modifying this code, the Licensee
 * terminates any agreement of support offered by WDCA, outlined in the 
 * provided Sweet Tooth Instore License. 
 * Upon discovery of modified code in the process of support, the Licensee 
 * is still held accountable for any and all billable time WDCA spent 
 * during the support process.
 * WDCA does not guarantee compatibility with any other framework extension. 
 * WDCA is not responsbile for any inconsistencies or abnormalities in the
 * behaviour of this code if caused by other framework extension.
 * If you did not receive a copy of the license, please send an email to 
 * support@wdca.ca or call 1-888-699-WDCA(9322), so we can send you a copy 
 * immediately.
 * 
 * @category   [TBT]
 * @package    [TBT_Rewardsinstore]
 * @copyright  Copyright (c) 2011 Sweet Tooth (http://www.sweettoothrewards.com)
 * @license    http://www.sweettoothrewards.com/instore/sweet_tooth_instore_license.txt
 */
?>
<?php if ($websites = $this->getWebsites()): ?>
    <p class="switcher"><label for="storefront_switcher"><?php echo $this->__('Choose Storefront') ?>:</label>
    <select name="storefront_switcher" id="storefront_switcher" onchange="return switchStorefront(this);">
        <option value=""><?php echo $this->__('All Storefronts') ?></option>
        <?php foreach ($websites as $website): ?>
            <?php $showWebsite = false ?>
            <?php /*foreach ($this->getStoreGroups($website) as $group): ?>
                <?php $showGroup = false*/ ?>
                <?php foreach ($this->getStorefronts($website) as $storefront): ?>
                    <?php if ($showWebsite == false): ?>
                        <?php $showWebsite = true ?>
                        <optgroup label="<?php echo $website->getName() ?>"></optgroup>
                    <?php endif ?>
                    <?php /*if ($showGroup == false): ?>
                        <?php $showGroup = true ?>
                        <optgroup label="&nbsp;&nbsp;&nbsp;<?php echo $group->getName() ?>">
                    <?php endif*/ ?>
                    <option value="<?php echo $storefront->getId() ?>"<?php if($this->getStorefrontId() == $storefront->getId()): ?> selected="selected"<?php endif ?>>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $storefront->getName() ?></option>
                <?php endforeach ?>
                <?php /*if ($showGroup): ?>
                    </optgroup>
                <?php endif ?>
            <?php endforeach*/ ?>
        <?php endforeach ?>
    </select>
    </p>
    <script type="text/javascript">
    //<![CDATA[
        function switchStorefront(obj)
        {
            if (obj.options[obj.selectedIndex].getAttribute('website') == 'true') {
                var selectionType = 'website';
            } else if (obj.options[obj.selectedIndex].getAttribute('group') == 'true') {
                var selectionType = 'group';
            } else {
                var selectionType = 'storefront';
            }
            
            var params = obj.value ? selectionType + '/' + obj.value + '/' : '';
            if (obj.switchParams) {
                params += obj.switchParams;
            }
            var select = null;
            //if ($('diagram_tab_orders_content').style.display != 'none') {
            //    select = $('order_orders_period');
            //} else if ($('diagram_tab_amounts_content').style.display != 'none') {
            //    select = $('order_amounts_period');
            //}
            params += (select && select.value) ? 'period/' + select.value + '/' : '';
            setLocation('<?php echo $this->getSwitchUrl() ?>' + params);
        }
    //]]>
    </script>
<?php endif; ?>
