<?php $_helper = Mage::helper('shutl'); ?>
<?php $methods = explode(',',$_helper->getServices()); ?>

<fieldset id="shutlOptions" style="display:">
		<?php echo $this->getBlockHtml('shutllegend'); ?>
		<input type="hidden" name="id" id="id" value="<?php echo $this->getRequest()->getParam('id'); ?>" />

		<?php if(in_array('shutl_now', $methods)): ?>

		<input type="radio" name="method" value="shutl_now" class="method"<?php echo ('shutl_later' != urldecode(Mage::getSingleton('core/session')->getShutlMethod())) ? ' checked="checked"': ''; ?> />
		<label class="shutl_now" for="shutl_now" style="background: url('<?php echo $_helper->getShutlNow(); ?>') 0% 50% no-repeat;"><?php echo Mage::helper('shutl')->getShutlNowHtml(); ?></label><br />
		<hr />
		<?php endif; ?>
		<?php if(in_array('shutl_later', $methods)): ?>
		
		<input type="radio" name="method" value="shutl_later" class="method"<?php echo ('shutl_later' == urldecode(Mage::getSingleton('core/session')->getShutlMethod())) ? ' checked="checked"': ''; ?> />
		<label class="shutl_later" for="shutl_later" style="background: url('<?php echo $_helper->getShutlLater(); ?>') 0% 50% no-repeat;"><?php echo Mage::helper('shutl')->getShutlLaterHtml(); ?></label><br />
		
			<?php
				$today		= $this->getToday();
				$startDate	= $this->getStartDate();
				$endDate	= $this->getEndDate();						
				$currentDate = $this->getCurrentDate();			
				$lastSelectableDate = $this->getLastSelectableDate();
				$selectedDate = $this->getSelectedDate();
				$counter	= 0;						

			?>
		<div id="shutlLaterOptions" style="<?php echo ('shutl_later' == urldecode(Mage::getSingleton('core/session')->getShutlMethod())) ? '': 'display: none'; ?>;">



			<div id="dateSelector" style="display: none;">
				<table>
					<thead>
						<tr>
							<td><?php echo $this->__('Mon'); ?></td>
							<td><?php echo $this->__('Tue'); ?></td>
							<td><?php echo $this->__('Wed'); ?></td>
							<td><?php echo $this->__('Thu'); ?></td>
							<td><?php echo $this->__('Fri'); ?></td>
							<td><?php echo $this->__('Sat'); ?></td>																												
							<td><?php echo $this->__('Sun'); ?></td>
						</tr>
					</thead>
					<tbody>
					<tr>
					<?php while ($currentDate < $endDate): ?>
							<?php
							$info = $_helper->getCalendarInfo($startDate, $lastSelectableDate, $today, $counter);
							$currentDate = $info['current_date'];
							?>
						<?php if ($counter > 0 && $counter % 7 == 0): ?>
						</tr>
						<tr>
						<?php endif; ?>
							<td<?php echo $info['class']; ?>>
								<?php echo $info['day']; ?>
								<span><?php echo $info['date']; ?></span>
							</td>
					<?php $counter++; endwhile; ?>
						</tr>
					</tbody>
				</table>
			</div>
			<input type="text" name="date" id="date" readonly="readonly" value="<?php echo ($selectedDate) ? $selectedDate : date($_helper->getDateFormat()); ?>" />
			<select name="time" id="time">
				<option value=""><?php echo $this->__('Select time'); ?></value>
			</select>
		</div>
		<hr />
		<?php endif; ?>
		<div id="shutlMessages">
		<?php echo $this->getChildHtml('global_messages') ?>
		</div>
				
</fieldset>