<?php 
    $_order  = $this->getOrder();
    $_source = $this->getSource();
?>
<?php if ($_source->getCustomerBalanceTotalRefunded()): ?>
<tr>
    <td <?php echo $this->getLabelProperties()?>>
        <?php echo Mage::helper('evogue_customerbalance')->__('Refunded to Store Credit'); ?>
    </td>
    <td <?php echo $this->getValueProperties()?>><?php echo $_order->formatPrice($_source->getCustomerBalanceTotalRefunded()) ?></td>
</tr>
<?php endif; ?>
