<?php
    $_order  = $this->getOrder();
    $_source = $this->getSource();
?>
<?php if ($_source->getCustomerBalanceAmount()): ?>
<tr>
    <td <?php echo $this->getLabelProperties()?>>
        <?php echo Mage::helper('evogue_customerbalance')->__('Store Credit'); ?>
    </td>
    <td <?php echo $this->getValueProperties()?>>-<?php echo $_order->formatPrice($_source->getCustomerBalanceAmount()) ?></td>
</tr>
<?php endif; ?>
