<?php 

Mage::getSingleton('customer/session')->setBeforeAuthUrl(Mage::getUrl("gifts.html"));

?>

	<div class="share-header clearfix">
		<div class="share-header-container section">
	
			<div class="gift-logo">
			</div>

			
			<div class="share-buttons">
				
				<div class="like-but share-but">
					<div class="fb-like" data-href="http://www.facebook.com/pages/Brandid/282808678428182" data-send="false" data-layout="button_count" data-width="100" data-show-faces="true"></div>
				</div>
			
				<div class="share-but follow">
					<a href="https://twitter.com/getbrandid" class="twitter-follow-button" data-show-count="true" data-lang="en">Follow @getbrandid</a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
				</div>
				
				<div class="share-but">
					<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.getbrandid.com/" data-text="Dirty boxers never got anyone laid. Designer brands auto-delivered for MEN. get #BRANDiD" data-count="horizontal" data-via="getbrandid">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
				</div>
								
				<div class="share-but gp">
					<g:plusone size="medium" href="https://www.getbrandid.com"></g:plusone>
				</div>
	
			</div>
			
			
			
			<div class="login-signup">
					<div class="login-signup-but"><a href="http://www.getbrandid.com/">Go back to getbrandid.com</a>
					</div>
			</div>
	
		</div>
	</div>

	
	<div id="title-block" class="title-block">
		<div class="title-block-inner clearfix">
			<div class="title-block-container section clearfix">		
				<div class="reg-form">
					<div class="product-sub-title">
						<span>They say the way to a man's heart</span><br/>
						<span>Is through his stomach.</span><br/><br/>
						<span>It's not. It's through his pants.</span>

					</div>
				</div>
				
			</div>
		</div>
	</div>
	
<div class="keep-calm-signup-container">
	
	
	<div class="commitment section">
		<div class="gift-landing section clearfix">
			<div class="gift-blurb">
				<span class="blurb-text">
					Bored of buying the same old tat for your man?
					Then why not buy him something he needs? Something that you’ll benefit from too?
					Something like a sexy pair of undies.<br/><br/>
					
					Granted, not all men will look like Beckham in his boxers, but smart, clean, hole-free undies might get your fella half way there.<br/><br/>
					
					So, how serious are you about this guy?  Whether it’s a short-term fling or a long-term thing - girlfriend, you’ve got options.
				</span>
				<div class="super-convert">
					<!-- Performable Super Conversion Button -->
					<script src='//d1nu2rn22elx8m.cloudfront.net/buttons/wQVx3/xCJAg-FCPcwxMTKUuN.js'></script>
					<!-- /Performable Super Conversion Button -->
				</div>
			</div>
			<div class="gift-image">
			</div>
		</div>
		
	</div>
	
</div>

<div class="grey-tilt-holder">
	<div class="grey-tilt clearfix">
			<div class="grey-tilt-container clearfix">
				<a class="invisibut" href="#how">
					<div class="learn-more chevron down">
						<div class="first-line block">LEARN MORE</div>
						<div class="chevron-triangle"></div>
					</div>
				</a>
				
				<div id="how" class="how section">
						<div class="vision-title">
							<span class="vision-title-text">How does it work?</span>
						</div>
					
					
					<div class="how-to-process">
						<div class="how-to-box">
							<div class="select-title">
								<span class="select-title-text">Select</span>
							</div>
							<div class="select-circle circle">
							</div>
							<div class="select-title red-title">
								<span class="select-title-text">Select a monthly plan</span>
							</div>
							
							<div class="select-triangle vert-chevron">
								<div class="select-triangle white moveable">
								</div>
								<div class="select-triangle grey">
								</div>
							</div>
						</div> <!-- end how to box -->
						
						<div class="how-to-box">
							<div class="select-title">
								<span class="select-title-text">Subscribe</span>
							</div>
							<div class="subscribe-circle circle">
								<div class="sub-detail detail-1">minimum of</div>
								<div class="sub-detail detail-2">30% off</div>
								<div class="sub-detail detail-3">the high street price</div>
							</div>
							<div class="select-title red-title">
								<span class="select-title-text">Automatic monthly billing</span>
							</div>
							
							<div class="subscribe-triangle vert-chevron">
								<div class="subscribe-triangle white moveable">
								</div>
								<div class="subscribe-triangle grey">
								</div>
							</div>
						</div> <!-- end how to box -->
			
						<div id="third-how" class="how-to-box last">
							<div class="select-title">
								<span class="select-title-text">Sorted</span>
							</div>
							<div id="sorted-cal" class="sorted-circle circle">
							</div>
							<div class="select-title red-title">
								<span class="select-title-text">Automatic monthly delivery</span>
							</div>
							
						</div> <!-- end how to box -->
						
					</div> <!-- end how to process -->						
					
					
				</div> <!-- end how section -->
		</div>
	</div>
</div>

	<div class="final-share section">
		<div class="vision-title">
			<span class="vision-title-text">Join the campaign to clothe sartorially challenged men</span>
		</div>
		<div class="box">
			Help spread the word and maybe, just maybe, you'll never have to see another pair of grey whites again.
		</div>
		
		<div class="share-buttons clearfix">
				
				<div class="like-but share-but">
					<div class="fb-like" data-href="http://www.facebook.com/pages/Brandid/282808678428182" data-send="true" data-layout="button_count" data-width="100" data-show-faces="true"></div>
				</div>
				
				<div class="share-but twitter">
					<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.getbrandid.com/" data-text="Ladies, join the campaign to clothe our sartorially challenged men #BRANDiD" data-count="horizontal" data-via="getbrandid">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
				</div>
				
				<div class="share-but gplus">
					<g:plusone size="medium" href="https://www.getbrandid.com/"></g:plusone>
				</div>
		</div>
	</div>
	

<script type="text/javascript">

	var $j = jQuery.noConflict();
	var w;
	var w_height;
	var image_bg_pause = 1;
		
	$j(function() {
		init();
		
				
		$j(window).scroll(function() {
			w = $j(this).scrollTop();
			var howTop = $j("#how").offset().top;
			
			if(w > $j("#how").data("scrolls")[0] && w < $j("#how").data("scrolls")[1]) {
	      	      
		      window.meeting_rel = w - ($j("#how").data("scrolls")[1] - 750);
		      
		      window.meeting_ratio = (Math.round((window.meeting_rel / ($j("#how").data("scrolls")[2] )) * 100 ) / 40);
			
/* 			console.log("w: %d",w); */
/* 			console.log("del: %d / scroll2: %d = ratio: %d",window.meeting_rel, $j("#how").data("scrolls")[2], window.meeting_ratio);    */

		      $j(".moveable").each(function(index) {
		      				      		
			      	var resetMargin = $j(this).data("original")[0];
			      	var fullMargin = $j(this).data("original")[1];
			      					   	if($j(this).data("moved")=="false") {
			          if(window.meeting_ratio > index) {
			          		$j(this).stop().animate({
			          			marginLeft: fullMargin
			          		},200,function() {
			          				$j(this).data("moved","true");
			          				$j("#third-how").animate({
			          					backgroundColor: "#d2002b"
			          				  }, 500 );
							        new Effect.Morph('sorted-cal', {
							            style: 'background-position:-2425px 0px',
							            duration: 10
							        });

							    });
									
			          	}
			        }
			        else {
						if(window.meeting_ratio < index) {
			          		$j(this).stop().animate({
			          			marginLeft: resetMargin
			          		},200,function() {
			          				$j(this).data("moved","false");
			          				$j("#third-how").animate({
			          					backgroundColor: "#fff"
			          				  }, 200 );
			          				new Effect.Morph('sorted-cal', {
							            style: 'background-position: 0px 0px',
							            duration: .2
							        });
			          			});
			          	}
			        }
			
				});
			}	


		   	
		   	if(w > $j("#title-block").data("scrolls")[0]) {
				$j.plax.disable();      			
			}
			if(w < $j("#title-block").data("scrolls")[0]) {
				$j.plax.enable();      			
			}
		
		});
	});
	
	function set_section_scrolls() {
	  w_height = $j(window).height();
	  $j(".section").each(function(){
	    var scrolls = new Array()
	    scrolls[0] = $j(this).offset().top - w_height;
	    scrolls[1] = $j(this).offset().top /* + $j(this).height() */;
	    scrolls[2] = scrolls[1] - scrolls[0];
	    $j(this).data("scrolls",scrolls);
	  });
	  
	  $j("#vision").each(function(){
	    var scrolls = new Array()
	    scrolls[0] = $j(this).offset().top - w_height;
	    scrolls[1] = $j(this).offset().top + $j(this).height();
	    scrolls[2] = scrolls[1] - scrolls[0];
	    $j(this).data("scrolls",scrolls);
	  });
	  
	  $j("#title-block").each(function(){
	    var scrolls = new Array()
	    scrolls[0] = $j(this).offset().top;
	    $j(this).data("scrolls",scrolls);
	  });
	  
	  $j(".moveable").each(function(){
		var marginBig;
		marginBig = parseInt($j(this).css('marginLeft').replace("px", ""),10);
	    marginBig += 30;
	    marginBig += "px";
	    
	    var original = new Array()
	    original[0] = $j(this).css('marginLeft');
	    original[1] = marginBig;
	    $j(this).data("original",original);
	    $j(this).data("moved","false");
	  });
	  
	}
	
	function init() {
	  set_section_scrolls();
	  $j(window).resize(set_section_scrolls);
	  	
	  $j(".hood-element").each(function(){
	    $j(this).hide();
	    $j(this).data("visible","false");
	  });
 
	  
	}
	
	
	function clearDefault(el) {
  		if (el.defaultValue==el.value) el.value = ""
	}

	

	$j(document).ready(function () {
		$j.localScroll();
		$j('a.invisibut').hover(
			function() {
				$j(this).addClass('red');
				},
			function() {
				$j(this).removeClass('red');
			});				
		

});

</script>