<?php 

Mage::getSingleton('customer/session')->setBeforeAuthUrl(Mage::getUrl("plans.html"));

?>


<div id="top" class="keep-calm-signup-container">
	
	<div class="ghost-header"></div>
	<div class="share-header clearfix">
		<div class="trans-back"></div>
		<div class="share-header-container section">
	
			<a id="logo" href="#top" class="logo-button" style="display:none;">
				<div class="gift-logo">
				</div>
			</a>
			
			
			
			<div class="convert">
				<a id="header-convert" href="/plans.html" class="convert" style="background:none;text-shadow:none;">Show me the Plans!</a>
			</div>
			<a href="#3" class="header-button">
				<span class="button-copy">Under the hood</span>
			</a>
			<a href="#2" class="header-button">
				<span class="button-copy">Our Vision</span>
			</a>
			<a href="#1" class="header-button">
				<span class="button-copy">How do plans work?</span>
			</a>

	
		</div>
		
	</div>
	
	
	
	<div class="big-fuckoff section">
		<div id="big-fuckoff-logo" class="logo section">
		</div>
		<a class="gift invisibut" href="/keep/calm/getgifted">
			<div class="subscribe-circle circle gift">
				<div id="gift1" class="sub-detail detail-1">not a man?</div>
				<div id="gift2" class="sub-detail detail-2">GIFT</div>
				<div id="gift3" class="sub-detail detail-3">a plan</div>
			</div>
		</a>
		
		
		<div class="shadow section">
		</div>

	</div>
	<div class="title-block first">
		<div class="title-block-inner clearfix">
			<div class="title-block-container section clearfix">		
				<div class="title section">
					<span class="first">I'm a man.</span><br/>
					<span id="signmeupnow" class="second">I don't read instructions.</span>
				</div>
			</div>
		</div>
	</div>
			
		
	<div class="signmeupnow-container section clearfix">
		
		<div id="action-section" class="action-section clearfix">
			
			<div class="commitment-caption">
				<span class="caption">No commitment or credit card required, just balls.</span>
			</div>

			
			<div class="convert-main clearfix">
				<a href="/plans.html" class="convert">Take me to the Plans Now!</a>
			</div>
			<div class="convert-middle">
				<span>OR</span>
			</div>
			<div class="convert-main">
				<div id="oa_social_login_convert"></div>
				<span id="1"></span>	
					<script type="text/javascript">
						 oneall.api.plugins.social_login.build("oa_social_login_convert", {
						  'providers' :  ['facebook', 'twitter'],
						  'callback_uri': '<?php echo $this->getUrl('arush-oneall/rpx/token_url', array('_forced_secure' => false)) ?>',
						  'css_theme_uri': '<?php echo $this->getSkinUrl(); ?>css/social-convert.css'
						 });
					</script>
			</div>
		</div>
		
		
		<div class="share-buttons">
			
			<div class="like-but share-but">
				<div class="fb-like" data-href="http://www.facebook.com/pages/Brandid/282808678428182" data-send="false" data-layout="button_count" data-width="100" data-show-faces="true"></div>
			</div>
		
			<div class="share-but follow">
				<a href="https://twitter.com/getbrandid" class="twitter-follow-button" data-show-count="true" data-lang="en">Follow @getbrandid</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			
			<div class="share-but">
				<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.getbrandid.com/" data-text="Dirty boxers never got anyone laid. Designer brands auto-delivered for MEN. get #BRANDiD" data-count="horizontal" data-via="getbrandid">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
			</div>
							
			<div class="share-but gp">
				<g:plusone size="medium" href="https://www.getbrandid.com"></g:plusone>
			</div>

		</div>
		
		
		
	</div>
				
					
	<div class="commitment-caption section">
		<div class="commitment-caption">
			<span class="caption">Plans? Whoa there buddy... we just met.</span>
		</div>
	</div>

	<div class="title-block first">
		<div class="title-block-inner clearfix">
			<div class="title-block-container section clearfix">		
				<div class="title section">
					<span class="first">I'm a man.</span><br/>
					<span class="second">I have commitment issues.</span>
				</div>
			</div>
		</div>
	</div>
	
	<div class="commitment-caption section">
		<div class="commitment-caption section">
			<span class="caption">That's OK. Let us explain what's going on.</span>
		</div>
	</div>
	
	
	<div class="grey-tilt-holder">
		<div class="grey-tilt clearfix">
				<div class="grey-tilt-container clearfix">
					<div class="vision section clearfix" id="take-to-plans">
						<div class="vision-title">
							<span class="vision-title-text">How do plans work?</span>
						</div>
						<div class="what box plans">Every man needs a plan, right? Well this is where you get yours. Choose the plan that suits you and let BRANDiD do the hard graft. We'll send your gear every month so your boxers are always box fresh. Select. Subscribe. Sorted. Capiche?
						</div>
						
						<div id="how" class="how section">
						
						
						
						<div class="how-to-process">
							<div class="how-to-box">
								<div class="select-title">
									<span class="select-title-text">Select</span>
								</div>
								<div class="select-circle circle">
								</div>
								<div class="select-title red-title">
									<span class="select-title-text">Select a monthly plan</span>
								</div>
								
								<div class="select-triangle vert-chevron">
									<div class="select-triangle white moveable">
									</div>
									<div class="select-triangle grey">
									</div>
								</div>
							</div> <!-- end how to box -->
							
							<div class="how-to-box">
								<div class="select-title">
									<span class="select-title-text">Subscribe</span>
								</div>
								<div class="subscribe-circle circle">
									<div class="sub-detail detail-1">minimum of</div>
									<div class="sub-detail detail-2">30% off</div>
									<div class="sub-detail detail-3">the high street price</div>
								</div>
								<div class="select-title red-title">
									<span class="select-title-text">Automatic monthly billing</span>
								</div>
								
								<div class="subscribe-triangle vert-chevron">
									<div class="subscribe-triangle white moveable">
									</div>
									<div class="subscribe-triangle grey">
									</div>
								</div>
							</div> <!-- end how to box -->
				
							<div id="third-how" class="how-to-box last">
								<div class="select-title">
									<span class="select-title-text">Sorted</span>
								</div>
								<div id="sorted-cal" class="sorted-circle circle">
								</div>
								<div class="select-title red-title">
									<span class="select-title-text">Automatic monthly delivery</span>
								</div>
								
							</div> <!-- end how to box -->
							
						</div> <!-- end how to process -->						
						
						
					</div> <!-- end how section -->
					
						<div class="plans-img">
						</div>
						
					</div>
					
					
					
					<div class="vision section clearfix">
						<div class="vision-title">
							<span class="vision-title-text">Boosters (coming soon)</span>
						</div>
						<div class="what box boosters">Because men shop to solve a problem.<br/>
						Delivered immediately in large quantities and with bulk discounts,
						Boosters ensure you're not in this situation again any time soon.<br/>
						If you're not the shopping type, choose Lucky Dip and we'll shop for you.
						</div>

						<div class="boosters-img first">
						</div>
						<div class="boosters-img second">
						</div>
						<div class="boosters-img third">
						</div>

						
					</div>
				</div> <!-- end grey tilt container -->
		</div> <!-- end grey tilt -->
	</div>
	
	
	
	<div class="quotes section clearfix">

		<div class="quote-box">
		<div class="apostrophe"><span>&lsquo;</span><span class="apostrophe2">&lsquo;</span></div>
		<span class="quote left">BRANDiD makes the hairs on my hairs stand up.</span>
		<div class="quote-triangle"></div>
		<span class="author">Wolverine</span>
		<span id="2" class="caption-small">aka Logan of the X-Men</span>
		<span class="caption-small">Man since… nobody knows</span></div>
		
		<div class="quote-box">
		<div class="apostrophe"><span>&lsquo;</span><span class="apostrophe2">&lsquo;</span></div>
		<span class="quote middle">I’d have shopped at BRANDiD if it had been around in my day.</span>
		<div class="quote-triangle"></div>
		<span class="author">Charlton Heston</span>
		<span class="caption-small">Actor of heroic roles</span>
		<span class="caption-small">Man since 1923</span></div>
		
		<div class="quote-box last">
		<div class="apostrophe"><span>&lsquo;</span><span class="apostrophe2">&lsquo;</span></div>
		<span class="quote right">It's not for me.</span>
		<div class="quote-triangle"></div>
		<span class="author">Gok Wan</span>
		<span class="caption-small">Not sure why he's famous</span>
		<span class="caption-small">Around since 1974</span></div>
		
	</div>
	
	<div class="grey-tilt-holder vision-block">
		<div class="grey-tilt clearfix">
			<div class="grey-tilt-container clearfix">
				<div class="vision section clearfix">
					<div class="vision-title">
						<span class="vision-title-text">Our Vision</span>
					</div>
					<div class="mandate box">
						<span class="vision-sub-title">Our <span class="red-text">Man</span>date</span>
						<div class="mandate-one-line block">
							We are reinventing shopping for men because the industry has forgotten about us.
							Why should we have to sift through poncy female-focused fashionista content just to get our clothes delivered? It's time to <a href="https://www.youtube.com/watch?v=aaas7GFbLHk&feature=related" target="_blank">take the power back.</a>
							<!-- if you're reading this, watch this one from '92! http://www.youtube.com/watch?v=cPHEgpWhkuQ&feature=related -->
						</div>
					</div>
					<div class="what-is box">
						<span class="vision-sub-title">What is BRANDiD?</span>
						<div class="what-is-oneliner">
							BRANDiD is a subscription service for designer basics… and a whole lot more. We love quality gear, big discounts and good humour. We hate fashionistas.
						</div>
					</div>
					
				</div>
			</div> <!-- end grey tilt container -->
		</div> <!-- end grey tilt -->
		<div class="commitment-caption reg section">
		<div class="reg-form">
			<div class="commitment-caption section ">
				<div class="commitment-caption">
					<span class="caption">Not ready for a plan? Register below and we'll be in touch when we have more cool stuff to tell you about.</span>
				</div>
			</div>
			
			<form action="/customer/account/create" method="get">
			  <input id="3" type="text" name="email" value="Register with your email address…" onFocus="clearDefault(this)"/>
			  <button class="convert" type="submit">Register Free</button>
			</form>
		</div>
	</div>
	</div>
	
	

	<div class="title-block first">
		<div class="title-block-inner clearfix">
			<div class="title-block-container section clearfix">		
				<div id="bigtop-title" class="title section">
					<span class="first">I'm a man.</span><br/>
					<span class="second">Show me what's under the hood.</span>
				</div>
			</div>
		</div>
	</div>
	
	
	<div class="price-compare section">
		
		<?php
		     echo  $this->getLayout()->createBlock('cms/block')->setBlockId('signup-products')->toHtml() ;
		?>

	</div>
	<div class="grey-tilt-holder">
		<div class="grey-tilt right-tilt clearfix">
			<div id="mags" class="hood section clearfix">
				
			<?php
			     echo  $this->getLayout()->createBlock('cms/block')->setBlockId('under-the-hood')->toHtml() ;
			?>
				
			</div>
	
		</div>
	</div>
	
	<div class="chev-group-wrap section">
		<div class="chevron-group final">
			<a class="invisibutred" href="#signmeupnow">
				<div class="chevron-triangle up red"></div>
				<div class="chevron up red">
					<div class="first-line block red">keep calm and</div>
					<div class="second-line block red">Sign me up!</div>
				</div>	
			</a>
			<a class="invisibut" href="#notaman">
				<div class="chevron down black">
					<div class="first-line block">Sounds cool, but it's just</div>
					<div class="second-line block">Not for me.</div>
					<div class="chevron-triangle"></div>
				</div>
			</a>
		</div>
	</div>
	
	<div id="notaman" class="final title section">
		<span class="first">I'm not a man.</span><br/>
		<a href="http://www.barbie.com/"><span class="second red">Get me the heck out of here.</a></span>
	</div>
	<div class="final-share section">
		<div class="vision-title">
			<span class="vision-title-text">Know someone who will like this?</span>
		</div>
		<div class="box">
			We're a small team with big ambitions, please help us spread the word.
		</div>
		
		<div class="share-buttons clearfix">
				
				<div class="like-but share-but">
					<div class="fb-like" data-href="http://www.facebook.com/pages/Brandid/282808678428182" data-send="false" data-layout="button_count" data-width="100" data-show-faces="true"></div>
				</div>
				
				<div class="share-but twitter">
					<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.getbrandid.com/" data-text="Men, rally the troops. It's time to take the power back. #shoplikeaman" data-count="horizontal" data-via="getbrandid">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
				</div>
				
				<div class="share-but gplus">
					<g:plusone size="medium" href="https://www.getbrandid.com/"></g:plusone>
				</div>
		</div>
	</div>
</div>


<script type="text/javascript">

	var $j = jQuery.noConflict();
	var w;
	var w_height;
	var image_bg_pause = 1;
		
	$j(function() {
		init();
		
				
		$j(window).scroll(function() {
			w = $j(this).scrollTop();
			var howTop = $j("#how").offset().top;
			var bigLogoTop = $j("#big-fuckoff-logo").offset().top - 100;
			var actionSection = $j("#action-section").offset().top - 30;
			
			/* fade the logo */
			if(w > bigLogoTop) {
				$j("#logo").fadeIn(500);
				
				
				
			}
			else {
				$j("#logo").fadeOut(500);
				
				
			}
			/* end fade the logo */

			/* fade the header convert button */
			if(w > actionSection) {
				$j("#header-convert").data("green","true");
				$j("#header-convert").css('background-clip','padding-box');
				$j("#header-convert").css('background-image','-moz-linear-gradient(center top , #66B84A, #51933A)');
				$j("#header-convert").css('background-image','-webkit-gradient(linear,left top,left bottom,color-stop(0, #66B84A),color-stop(1, #51933A))');
				$j("#header-convert").css('filter','progid:DXImageTransform.Microsoft.gradient(startColorStr=\'#66b84a\', EndColorStr=\'#51933a\')');
				$j("#header-convert").css('-ms-filter','"progid:DXImageTransform.Microsoft.gradient(startColorStr=\'#66b84a\', EndColorStr=\'#51933a\')"');
				$j("#header-convert").css('background-color','#51933A');
				$j("#header-convert").css('color','white');
				$j("#header-convert").css('text-shadow','0pt -1px 0pt black');
			}
			else {
				$j("#header-convert").data("green","false");
				$j("#header-convert").css('background','none');
				$j("#header-convert").css('color','black');
				$j("#header-convert").css('text-shadow','none');
			}
			/* end fade the header convert button */
			
			if(w > $j("#how").data("scrolls")[0] && w < $j("#how").data("scrolls")[1]) {
	      	      
		      window.meeting_rel = w - ($j("#how").data("scrolls")[1] - 750);
		      
		      window.meeting_ratio = (Math.round((window.meeting_rel / ($j("#how").data("scrolls")[2] )) * 100 ) / 40);
			
/* 			console.log("w: %d",w); */
/* 			console.log("del: %d / scroll2: %d = ratio: %d",window.meeting_rel, $j("#how").data("scrolls")[2], window.meeting_ratio);    */

		      $j(".moveable").each(function(index) {
		      				      		
			      	var resetMargin = $j(this).data("original")[0];
			      	var fullMargin = $j(this).data("original")[1];
			      					   	if($j(this).data("moved")=="false") {
			          if(window.meeting_ratio > index) {
			          		$j(this).stop().animate({
			          			marginLeft: fullMargin
			          		},200,function() {
			          				$j(this).data("moved","true");
			          				$j("#third-how").animate({
			          					backgroundColor: "#d2002b"
			          				  }, 500 );
							        new Effect.Morph('sorted-cal', {
							            style: 'background-position:-2425px 0px',
							            duration: 10
							        });

							    });
									
			          	}
			        }
			        else {
						if(window.meeting_ratio < index) {
			          		$j(this).stop().animate({
			          			marginLeft: resetMargin
			          		},200,function() {
			          				$j(this).data("moved","false");
			          				$j("#third-how").animate({
			          					backgroundColor: "#fff"
			          				  }, 200 );
			          				new Effect.Morph('sorted-cal', {
							            style: 'background-position: 0px 0px',
							            duration: .2
							        });
			          			});
			          	}
			        }
			
				});
			}	

			
			if(w > $j("#mags").data("scrolls")[0] && w < $j("#mags").data("scrolls")[1]) {
      
		      window.group_rel = w - ($j("#mags").data("scrolls")[0] + 650);
		      window.group_ratio = (Math.round((window.group_rel / ($j("#mags").data("scrolls")[2] - 650)) * 100) / 25);      
		    	

		    
   		      $j(".hood-element").each(function(index) {
		        if($j(this).data("visible")=="false") {
		          if(window.group_ratio > index) $j(this).fadeIn(600,
		          	function() {
		          		$j(this).data("visible","true");
								          		
		          		});
		        }
		        else {
		          if(window.group_ratio < index) $j(this).fadeOut(600,function() {$j(this).data("visible","false")});
		        }
		 
		      });
		      
		    }
		   			
		});
	});
	
	function set_section_scrolls() {
	  w_height = $j(window).height();
	  $j(".section").each(function(){
	    var scrolls = new Array()
	    scrolls[0] = $j(this).offset().top - w_height;
	    scrolls[1] = $j(this).offset().top /* + $j(this).height() */;
	    scrolls[2] = scrolls[1] - scrolls[0];
	    $j(this).data("scrolls",scrolls);
	  });
	  
	  $j("#vision").each(function(){
	    var scrolls = new Array()
	    scrolls[0] = $j(this).offset().top - w_height;
	    scrolls[1] = $j(this).offset().top + $j(this).height();
	    scrolls[2] = scrolls[1] - scrolls[0];
	    $j(this).data("scrolls",scrolls);
	  });
	  
	  $j("#title-block").each(function(){
	    var scrolls = new Array()
	    scrolls[0] = $j(this).offset().top;
	    $j(this).data("scrolls",scrolls);
	  });
	  
	  $j(".moveable").each(function(){
		var marginBig;
		marginBig = parseInt($j(this).css('marginLeft').replace("px", ""),10);
	    marginBig += 30;
	    marginBig += "px";
	    
	    var original = new Array()
	    original[0] = $j(this).css('marginLeft');
	    original[1] = marginBig;
	    $j(this).data("original",original);
	    $j(this).data("moved","false");
	  });
	  
	}
	
	function init() {
	  set_section_scrolls();
	  $j(window).resize(set_section_scrolls);
	  	
	  $j(".hood-element").each(function(){
	    $j(this).hide();
	    $j(this).data("visible","false");
	  });
	  
	  $j("#logo").data("visible","false"); 
	  
	}	
	
	function clearDefault(el) {
  		if (el.defaultValue==el.value) el.value = ""
	}

	

	$j(document).ready(function () {
		$j.localScroll();
		$j('a.invisibut').hover(
			function() {
				$j(this).addClass('red');
				},
			function() {
				$j(this).removeClass('red');
			});				
		

});

</script>
<script type="text/javascript">
			
				
			$j('a.gift.invisibut').hover(
				    
				function () {
					$j('#gift1').css('-webkit-transform','rotate(0deg)');
					$j('#gift1').css('-moz-transform','rotate(0deg)');
					$j('#gift1').css('-ms-transform','rotate(0deg)');
					$j('#gift1').css('-0-transform','rotate(0deg)');
					$j('#gift1').css('transform','rotate(0deg)');

				    $j('.gift.invisibut').find('.subscribe-circle').css('background-color','#d2002b');
				    
				    $j('#action-section').find('a.convert').css('background-image','-moz-linear-gradient(center top , #bbb, #aaa)');
				    $j('#action-section').find('a.convert').css('background-image','-webkit-gradient(linear,left top,left bottom,color-stop(0, #bbb),color-stop(1, #aaa))');
				    $j('#action-section').find('a.convert').css('filter','progid:DXImageTransform.Microsoft.gradient(startColorStr=\'#bbb\', EndColorStr=\'#aaa\')');
				    $j('#action-section').find('a.convert').css('-ms-filter','"progid:DXImageTransform.Microsoft.gradient(startColorStr=\'#bbb\', EndColorStr=\'#aaa\')"');
				  }, 
				  function () {
					$j('#gift1').css('-webkit-transform','rotate(180deg)');
					$j('#gift1').css('-moz-transform','rotate(180deg)');
					$j('#gift1').css('-ms-transform','rotate(180deg)');
					$j('#gift1').css('-0-transform','rotate(180deg)');
					$j('#gift1').css('transform','rotate(180deg)');
					
				    $j('.gift.invisibut').find('.subscribe-circle').css('background-color','#333');
				    
				    $j('#action-section').find('a.convert').css('background-image','-moz-linear-gradient(center top , #66B84A, #51933A)');
				    $j('#action-section').find('a.convert').css('background-image','-webkit-gradient(linear,left top,left bottom,color-stop(0, #66B84A),color-stop(1, #51933A))');
				    $j('#action-section').find('a.convert').css('filter','progid:DXImageTransform.Microsoft.gradient(startColorStr=\'#66B84A\', EndColorStr=\'#51933A\')');
				    $j('#action-section').find('a.convert').css('-ms-filter','"progid:DXImageTransform.Microsoft.gradient(startColorStr=\'#66b84a\', EndColorStr=\'#51933a\')"');

				  }
			);				
			
		</script>
		
<script type="text/javascript">
			// fix hover for header convert button
				
			$j('#header-convert').hover(
				    
				function () {
					if($j("#header-convert").data("green")=="false") {
						$j(this).css('color', '#d2002b');
					}
					
				  }, 
				  function () {
					if($j("#header-convert").data("green")=="false") {
						$j(this).css('color', '#000');
					}
				  }
			);				
			
		</script>


