<?php 
/**
 * Manufacturers extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    Manufacturers
 * @author     Kamran Rafiq Malik <kamran.malik@unitedsol.net>
 * @copyright  Copyright 2010 © free-magentoextensions.com All right reserved
 */
?>
<style>
.product_container { width:100%; margin:0 auto; margin-top:0px; padding-left:35px; }
.row_main { width:100%; height:auto; }
.main_div { width:180px; float:left; margin-left:30px; }
.heading { font-family:Arial; font-size:12px; color:#FFF; font-weight:bold; padding-left:10px; float:left; padding-top:0px; }
.text { font-family:arial; font-size:12px; color:#676767; font-style:italic; font-weight:normal; line-height:18px; }

div.casestudy {
	width: 135px;
	margin: 0 10px 10px 0;
	/*background-color: #ccc;*/
	float: left;
	text-align: left;
}

div.casestudy div.who {
	background-color: #222;
	padding: 5px;
}

div.casestudy div.who h3, div.casestudy div.who h4 {
	margin: 0;
	padding: 2px 0 0 0;
	color: #fff;
	line-height: 1em;
}

div.casestudy div.who h3 {
	font-size: 14px;
}

div.casestudy div.who h4 {
	font-size: 12px;
	font-weight: normal;
	color: #E8ECDC;
}

div.casestudy div.what {
	font-size: 14px;
	text-align: left;
	padding: 5px 0 0 5px;
	font-family: georgia;
	font-style: italic;
	/*background-color: #F5F6F7;*/
	line-height: 1.1em;
}

div.casestudies div.casestudy img.play {
	position: absolute;
	border:0;
}

div.end {
	margin-right: 0;
}

</style>
<div class="product_container">
<?php $_productCollection=$this->getManufacturerProducts() ?>
<?php $_collectionSize = $_productCollection->count() ?>
	<?php if ( count($_productCollection) == 0 ) : ?>
		<p class="text_1"><?php echo $this->__('No products yet for this manufacturer...'); ?></p>
	<?php else : ?>
    	 <div class="row_main">
        <?php $_collectionSize = count($_productCollection); ?>
        <?php $_columnCount = 6; ?>
		<?php $i=1; foreach ( $_productCollection as $_product ) : ?> 	
    				<div class="casestudies">
                    	<div class="casestudy">
                        		  <?php
                                  try{
								  ?>
                                  <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
                                  <?php } catch (Exception $e) { 
								  		echo '<img src="" width="135" height="135" />';
								  }
   											 
								  ?>

                                  <div class="window_content video" id="rbird_video" style="display: none;"></div>
                                  <div class="who">
                                    <h3><?php echo $this->htmlEscape($_product->getName()) ?></h3>
                                  </div>
                                  <div class="what">
                                  	<?php echo $_product->getFormatedPrice() ?>
                                  </div>
                        </div>
                	</div>
              
             <?php if($i % 6 == 0): ?>
             	</div>
                <br  style="clear:both;" /><br />
                <div class="row_main">
             <?php endif ?>
             <?php $i++; ?>            
  		<?php endforeach; ?>
</div>      
<br style="clear:both;" />
<?php endif; ?>
</div>