<?php if ($this->getIsReadonly()):?>
<?php $_readonly = ' disabled="disabled" ';?>
<?php else: ?>
<?php $_readonly = '';?>
<?php endif; ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('evogue_targetrule')->__('Rule-based Settings') ?></h4>
    </div>
    <div class="fieldset">
        <div class="hor-scroll">
        <table cellspacing="0" class="form-list" id="table_catalog_targetrule">
        <tr>
            <td class="label"><label for="<?php echo $this->getFieldName('position_limit'); ?>"><?php echo Mage::helper('evogue_targetrule')->__('Rule-based Positions') ?></label></td>
            <td class="value"><input type="text" class="input-text validate-number" id="<?php echo $this->getFieldName('position_limit'); ?>" name="product[<?php echo $this->getFieldName('position_limit'); ?>]" value="<?php echo (int)$this->getPositionLimit();?>" <?php echo $this->isDefault('position_limit') || $this->getIsReadonly() ? 'disabled="true" ' : ''; ?>/>
                <input type="checkbox" id="<?php echo $this->getFieldName('position_limit'); ?>_default" name="product[<?php echo $this->getFieldName('position_limit'); ?>_default]" value="1" onclick="targetruleSetDefault(this, '<?php echo $this->getFieldName('position_limit'); ?>');" class="checkbox" <?php echo $_readonly ?><?php echo $this->isDefault('position_limit') ? 'checked' : ''; ?>/>
                <label for="<?php echo $this->getFieldName('position_limit'); ?>_default" class="normal"><?php echo Mage::helper('evogue_targetrule')->__('Use Config Settings') ?></label>
            </td>
            <td class="value scope-label"><?php echo Mage::helper('evogue_targetrule')->__('[GLOBAL]') ?></td>
        </tr>
        <tr>
            <td class="label"><label for="<?php echo $this->getFieldName('position_behavior'); ?>"><?php echo Mage::helper('evogue_targetrule')->__('Position Behavior') ?></label></td>
            <td class="value"><select id="<?php echo $this->getFieldName('position_behavior'); ?>" name="product[<?php echo $this->getFieldName('position_behavior'); ?>]" class="select" <?php echo $this->isDefault('position_behavior') || $this->getIsReadonly() ? 'disabled="true"' : ''; ?>>
            <?php
            foreach ($this->getPositionBehaviorOptions() as $key=>$value) {
                echo "<option value=\"{$key}\"";
                echo ($key == $this->getPositionBehavior())?'selected':'';
                echo ">{$value}</option>";
            }
            ?>
            </select>
            <input type="checkbox" id="<?php echo $this->getFieldName('position_behavior'); ?>_default" name="product[<?php echo $this->getFieldName('position_behavior'); ?>_default]" value="1" onclick="targetruleSetDefault(this, '<?php echo $this->getFieldName('position_behavior'); ?>');" class="checkbox" <?php echo $_readonly?><?php echo $this->isDefault('position_behavior') ? 'checked' : ''; ?>/>
            <label for="<?php echo $this->getFieldName('position_behavior'); ?>_default" class="normal"><?php echo Mage::helper('evogue_targetrule')->__('Use Config Settings') ?></label>
            <td class="value scope-label"><?php echo Mage::helper('evogue_targetrule')->__('[GLOBAL]') ?></td>
        </tr>
        </table>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
targetruleSetDefault = function (check, elementId) {
    var el = $(elementId).disabled = check.checked;
}
//]]>
</script>
