<!-- Innovate Analytics tracking beacon  -->

<?php if(Mage::getStoreConfig('analytics/track/analytics_invitation_on')) {
		echo Mage::getStoreConfig('analytics/track/analytics_invitation_landing_code');
	}
?>

<!-- END Innovate Analytics tracking beacon  -->

<div class="referrals">

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="refer-form">
<?php echo $this->getChildHtml('refer_form'); ?></div>
<div class="affiliate"><?php echo $this->getChildHtml('affiliate'); ?></div>
<div class="history"><?php echo $this->getChildHtml('history'); ?></div>
<div class="preferences"><?php echo $this->getChildHtml('preferences'); ?></div>

</div>