<?php
?>
<script type="text/javascript"> 
document.observe("dom:loaded", function() {
	var notification_elem = $('facebook-like-rewards-notification');
	var flr = new FacebookLikeReward('<?php echo $this->getRewardUrl() ?>', $('facebook-like-rewards-notification-content'), '<?php echo $this->getPageKey(); ?>', $('facebook-like-rewards-ajax-loading'));
	
	eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};if(!''.replace(/^/,String)){while(c--){d[c.toString(a)]=k[c]||c.toString(a)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('1.7=1.9||0(){};1.9=0(){1.7();3.2.5(\'c.b\',0(4){3.2.5(\'a.i\',0(4){6.d()});3.2.5(\'a.e\',0(4){6.g()});h(8){8.f()}})};',19,19,'function|window|Event|FB|response|subscribe|flr|oldFbAsyncInit|notification_elem|fbAsyncInit|edge|render|xfbml|onLike|remove|show|onUnLike|if|create'.split('|'),0,{}));

});

</script>