				<div id="oa_social_login_container"></div>
			
				<script type="text/javascript">
					 oneall.api.plugins.social_login.build("oa_social_login_container", {
					  'providers' :  ['facebook'], 
					  'callback_uri': '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>arush-oneall/rpx/token_url/',
					  'css_theme_uri': 'https://cdn.oneall.com/css/api/socialize/themes/connect_vertical.css'
					 });
				</script>
