<?php $_product = Mage::getModel('catalog/product')->load(Mage::registry('current_product')->getId());?>
<?php $_helper = $this->helper('catalog/output'); ?>



<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="sliders">
<div class="black-title-bar">What's in the plan?</div>


<?php /*

<div class="plan-explanation">
	<?php $block = Mage::getModel('cms/block')->load('plan-randomness-explanation');?>
    <?php echo $block->getContent(); ?>
</div>
*/

?>
	<?php /* the code below is also in the media page because we need it to appear for giftcard products, catalog/product/view/media.phtml */ ?>
	
	<?php if($_product->getData('num_socks') > 0)  { ?>
	<div id="planOther" class="clearfix">

		<div class="item-pic-left"><img class="plans-item-img" src="<?php echo Mage::getDesign()->getSkinUrl('images/plans/socks.jpg');?>" />
		</div>
		
		<div class="brands-list">
			<span class="context">Socks From:</span><br/><br/>
			<span class="brands">Armani</span><br/>
			<span class="brands">Calvin Klein</span><br/>
			<span class="brands">Hugo Boss</span><br/>
			<span class="brands">Roberto Cavalli</span><br/>
			<span class="brands">Belstaff</span><br/>
			<span class="brands">…and similar</span><br/><br/>
			<span class="context">Minimum RRP: £10</span>
		</div>
	</div>
		<?php 
		};
	
	?>
	
	<?php if($_product->getData('num_boxers') > 0)  { ?>
	<div id="planOther" class="clearfix">

		<div class="item-pic-left"><img class="plans-item-img" src="<?php echo Mage::getDesign()->getSkinUrl('images/plans/underwear.jpg');?>" />
		</div>
		
		<div class="brands-list">
			<span class="context">Boxers From:</span><br/><br/>
			<span class="brands">Armani</span><br/>
			<span class="brands">Calvin Klein</span><br/>
			<span class="brands">Dolce & Gabbana</span><br/>
			<span class="brands">Diesel</span><br/>
			<span class="brands">Dior</span><br/>
			<span class="brands">…and similar</span><br/><br/>
			<span class="context">Minimum RRP: £25</span>
		</div>
	</div>
		<?php 
		};
	
	?>
	
	<?php if($_product->getData('num_tshirts') > 0)  { ?>
	<div id="planOther" class="clearfix">

		<div class="item-pic-left"><img class="plans-item-img" src="<?php echo Mage::getDesign()->getSkinUrl('images/plans/tee.jpg');?>" />
		</div>
		
		<div class="brands-list">
			<span class="context">T-shirts From:</span><br/><br/>
			<span class="brands">Armani</span><br/>
			<span class="brands">Belstaff</span><br/>
			<span class="brands">Calvin Klein</span><br/>
			<span class="brands">Dolce & Gabbana</span><br/>
			<span class="brands">Dior</span><br/>
			<span class="brands">…and similar</span><br/><br/>
			<span class="context">Minimum RRP: £40</span>
		</div>
	</div>
		<?php 
		};
	
	?>
	
	<?php if($_product->getData('num_shirts') > 0)  { ?>
	<div id="planOther" class="clearfix">

		<div class="item-pic-left"><img class="plans-item-img" src="<?php echo Mage::getDesign()->getSkinUrl('images/plans/shirt.jpg');?>" />
		</div>
		
		<div class="brands-list">
			<span class="context">Shirts From:</span><br/><br/>
			<span class="brands">Armani</span><br/>
			<span class="brands">Calvin Klein</span><br/>
			<span class="brands">Dolce & Gabbana</span><br/>
			<span class="brands">Gucci</span><br/>
			<span class="brands">Valentino</span><br/>
			<span class="brands">…and similar</span><br/><br/>
			<span class="context">Minimum RRP: £125</span>
		</div>
	</div>
		<?php 
		};
	
	?>
	

</div>
<div class="plan product-info">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

		<div class="discount-triangle-container">
			<span class="discount-number"><?php echo $_product->getDiscount() ; ?> % off</span>
			<span class="discount-label">RRP</span>
		</div>

		<div class="discount-triangle">
		</div>		
		<div class="price-box">
			<span class="price"><?php echo 'RRP &pound;' . number_format($_product->getPrice(), 0); ?></span>
			<span class="special-price"><?php echo 'Plan Price &pound;' . number_format($_product->getSpecialPrice(), 0); ?></span>
		</div>
	
	    <div class="container2">
	    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
	    </div>
	    
	    <div class="bottom-stuff">
		    <div class="add-to-box">
		        <?php echo $this->getChildHtml('addtocart') ?>
		        <?php echo $this->getChildHtml('addto') ?>
				<div class="delivery-date">
					<?php $profile = Mage::helper('randomquote')->getProfileEasyDate(); /*remove Easy when enabling delivery drops*/?>
					<?php echo $this->__('This plan delivers between <br/><span class="actual-date">') . $profile['delivery_date'] . $this->__('</span><br/>and<br/><span class="actual-date">') . $profile['delivery_date2'] . $this->__('</span><br/> and every month after that');?>	
				</div>
		    </div>
		    <div class="extra-info">
		       		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('plan-text-' . $_product->getSku())->toHtml(); ?>
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('plan-text-common')->toHtml(); ?>
		    </div>
	    </div>
    </form>
    
</div>
<?php
$upsells = $_product->getUpSellProductCollection()->addAttributeToSort('position', 'asc');
if ($upsells->count() > 0):
?>
<div class="upsells">
	<h1 class="black-title-bar"><?php echo $this->__('Our Plans'); ?></h1>
	<ul>
	<?php foreach($upsells as $upsell): ?>
		<?php $upsellProduct = Mage::getModel('catalog/product')->load($upsell->getId()); ?>
		<li>
			<h3><span class="title">the</span><? echo $upsellProduct->getName(); ?></h3>
			<span class="price"><?php echo Mage::helper('core')->currency($upsellProduct->getPrice());?></span><br />
			<span class="special-price"><?php echo Mage::helper('core')->currency($upsellProduct->getSpecialPrice());?></span>
			<button class="button"><span><span><?php echo $this->__('View plan'); ?></span></span></button>
		</li>
	<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>


<script type="text/javascript">

    //<![CDATA[
	$('product-options-wrapper').select('label').each(function(obj){
		if (obj.innerHTML.toLowerCase().indexOf('shoe') >= 0) {
			obj.up().next().addClassName('sock-bg');
			obj.up().next().innerHTML += '<span class="option-number"><?php echo $_product->getNumSocks(); ?>x</span>';
		} else if (obj.innerHTML.toLowerCase().indexOf('t-shirt') >= 0) {
			obj.up().next().addClassName('tshirt-bg');	
			obj.up().next().innerHTML += '<span class="option-number"><?php echo $_product->getNumTshirts(); ?>x</span>';			
		} else if (obj.innerHTML.toLowerCase().indexOf('boxer') >= 0) {
			obj.up().next().addClassName('boxer-bg');		
			obj.up().next().innerHTML += '<span class="option-number"><?php echo $_product->getNumBoxers(); ?>x</span>';			
		} else if (obj.innerHTML.toLowerCase().indexOf('shirt') >= 0) {
			obj.up().next().addClassName('shirt-bg');	
			obj.up().next().innerHTML += '<span class="option-number"><?php echo $_product->getNumShirts(); ?>x</span>';
				
		}
	});


        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>