<?php 
 $referer = '';
if (isset($_SERVER['HTTP_REFERER'])) { $refer = $_SERVER['HTTP_REFERER']; } // Get referer

if (Mage::app()->getRequest()->getActionName() != 'noRoute') { // Only do our auth logic if we did not hit a 404 page

	Mage::getSingleton('customer/session')->setBeforeAuthUrl(Mage::getUrl("plans.html"));	

	// if(!Mage::getSingleton('customer/session')->isLoggedIn() ) { // Only redirect to login if customer is not logged in AND referer is not from Brandid
	    echo "<script type=\"text/javascript\">window.location='".$this->getUrl('keep/calm/signmeup', array('_forced_secure' => false))."';</script>";  
	// }
}

/* && strpos($referer, Mage::getBaseUrl()) < 0 */ ?>
